/* Required observation gaps: local 2022 science standards + their explanations.
 * These are explicitly schematic school models, not acquired measurements.
 * No high-school elective extensions, clinical procedures or unsupervised reagents.
 */
function scienceCoreFactory({line,label,rect,jar,field},existing={}) {
 const result={};
 const circle=(x,y,r,fill)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${fill}"/>`;
 const ellipse=(x,y,rx,ry,fill)=>`<ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${fill}"/>`;
 const stages=field('stage','관찰 시점',[['before','처음'],['after','변화 뒤']]);
 const check=(question,choices,answer,why)=>{const shift=[...question].reduce((n,c)=>n+c.charCodeAt(0),0)%choices.length;return{question,choices:choices.slice(shift).concat(choices.slice(0,shift)),answer:String((+answer-shift+choices.length)%choices.length),why};};
 const schematic='특징을 비교하는 설명 그림이며 실물 사진이나 실제 측정 결과가 아닙니다.';
 function add(slug,spec){
  const old=existing[slug];
  if(!old){result[slug]=spec;return;}
  const fields=(p,s)=>typeof p.fields==='function'?p.fields(s):p.fields;
  result[slug]={title:spec.title,codes:[...new Set([...old.codes,...spec.codes])],initial:{...old.initial,...spec.initial,pathway:'core'},
   fields:s=>[field('pathway','관찰 선택',[['core',spec.title],['previous',old.title]]),...fields(s.pathway==='core'?spec:old,s)],
   view:s=>s.pathway==='core'?spec.view(s):old.view(s)};
 }
 add('microbes',{
  title:'버섯·곰팡이·해캄·짚신벌레·세균 관찰',codes:['4과12-01'],initial:{sample:'mushroom',focus:'whole'},
  fields:[field('sample','준비된 표본',[['mushroom','버섯'],['mold','곰팡이'],['algae','해캄'],['paramecium','짚신벌레'],['bacteria','세균']]),field('focus','관찰 초점',[['whole','전체 모습'],['detail','특징 살피기']])],
  view(s){let svg='',text='',detail=s.focus==='detail';
   if(s.sample==='mushroom'){svg=rect(205,120,50,115,'#e7d9bd')+'<path d="M115 130 Q135 20 230 35 Q325 20 345 130 Z" fill="#bc8c60"/>'+ellipse(230,130,114,20,'#e5c39b');if(detail)for(let i=0;i<11;i++)svg+=line(230,136,125+i*21,130,'#9b7557',2);svg+=label(detail?'갓 아래 주름':'갓과 자루',230,280);text='버섯은 갓과 자루가 있는 종류가 있습니다. 갓 아래에 주름이 보입니다. 썩은 나무나 축축한 땅 등에서 볼 수 있으며, 종류에 따라 모습과 사는 곳이 다릅니다.';}
   if(s.sample==='mold'){for(let i=0;i<8;i++){const x=110+i*34,y=85+(i%3)*30;svg+=line(230,240,x,y,'#91a285',3)+circle(x,y,detail?13:8,'#57675c');}svg+=label('실처럼 얽힌 부분',230,280);text='곰팡이는 가느다란 실처럼 얽힌 부분과 끝의 둥근 부분이 관찰되는 종류가 있습니다. 습기가 있는 빵이나 과일 등에 자랄 수 있습니다.';}
   if(s.sample==='algae'){for(let i=0;i<6;i++){svg+=rect(85+i*48,95,46,95,'#b5da99');svg+='<path d="M'+(89+i*48)+' 170 Q'+(110+i*48)+' 75 '+(125+i*48)+' 165" fill="none" stroke="#428448" stroke-width="5"/>';}svg+=label(detail?'초록색 띠가 나선처럼 보임':'여러 마디가 실처럼 이어짐',230,260);text='해캄은 연못이나 물살이 느린 민물에서 볼 수 있습니다. 초록색이며 여러 마디가 실처럼 이어져 있고, 확대하면 안쪽에 나선 모양의 초록색 띠가 보입니다.';}
   if(s.sample==='paramecium'){svg=ellipse(230,145,110,65,'#cbdcd9');for(let i=0;i<30;i++){const a=i*Math.PI/15;svg+=line(230+110*Math.cos(a),145+65*Math.sin(a),230+123*Math.cos(a),145+78*Math.sin(a),'#759793',2);}svg+=ellipse(215,140,17,24,'#90aaa9')+label(detail?'몸 둘레의 짧은 털':'길쭉한 몸',230,270);text='짚신벌레는 유기물이 있는 민물 등에서 볼 수 있습니다. 길쭉한 몸 둘레에 짧은 털이 많고, 이를 움직여 헤엄칩니다. 정지 그림에서는 실제 움직임을 관찰할 수 없습니다.';}
   if(s.sample==='bacteria'){for(let i=0;i<9;i++)svg+=rect(110+(i%3)*85,65+Math.floor(i/3)*65,40,18,'#90bab0');svg+=label('막대 모양 세균의 확대 그림',230,285);text='세균에는 막대 모양이나 둥근 모양 등 여러 모습이 있습니다. 흙과 물, 다른 생물의 몸 등 다양한 곳에 살며, 눈으로 하나하나 구별하기 어렵습니다.';}
   return{svg,text,note:schematic+' 서로 같은 배율이 아닙니다. 교사가 준비한 표본·사진으로 관찰하고, 곰팡이와 세균을 직접 배양하거나 만지거나 냄새 맡지 않습니다.',check:check('해캄의 관찰 특징으로 맞는 것은?',['실처럼 이어진 초록색 모습','갓과 자루가 있는 모습','모든 종류가 막대 모양'],'0','해캄은 초록색 마디가 실처럼 이어진 모습을 보입니다. 사는 곳과 모습으로 관찰 기록을 정리합니다.')};}
 });
 add('solubility',{
  title:'용질 종류·용액 진하기 비교',codes:['6과03-01','6과03-02'],initial:{kind:'solute',dose:'small',amount:'more',water:'same'},
  fields:s=>[field('kind','비교 실험',[['solute','소금과 설탕'],['float','진하기와 뜨는 정도']]),...(s.kind==='solute'?[field('dose','같은 무게씩 넣기',[['small','적은 양'],['large','충분히 많은 양']])]:[field('amount','오른쪽 용액의 설탕 양',[['same','왼쪽과 같음'],['more','더 많음']]),field('water','오른쪽 용액의 물의 양',[['same','왼쪽과 같음'],['more','더 많음']])])],
  view(s){if(s.kind==='solute'){const large=s.dose==='large';return{svg:jar(65,125,'#b9deed')+jar(285,125,'#b9deed')+(large?rect(77,211,85,15,'#f9fafb')+rect(297,220,85,6,'#f9fafb'):'')+label('소금',120,35)+label('설탕',340,35)+label(large?'남은 양이 더 많음':'모두 녹음',120,275)+label(large?'남은 양이 더 적음':'모두 녹음',340,275),text:large?'같은 온도·같은 양의 물에 같은 무게의 소금과 설탕을 충분히 많이 넣고 충분히 저었습니다. 이 모형에서는 설탕이 더 많이 녹아 소금보다 바닥에 남은 양이 적습니다. 용질 종류에 따라 녹는 양이 달라집니다.':'적은 양을 넣으면 둘 다 모두 녹을 수 있습니다. 이 결과만으로 두 용질이 최대로 녹는 양이 같다고 판단할 수 없습니다.',note:'실온의 소금·설탕 비교를 단순화했습니다. 높이는 실제 용해량 수치가 아닙니다. 물의 양·온도·넣는 무게와 충분히 젓는 조건을 같게 하며, 녹는 빠르기와 최대로 녹는 양을 구분합니다.',check:check('용질 종류의 영향만 비교하려면 같게 할 조건은?',['물의 양과 온도, 넣는 용질의 무게','용질의 종류만','물의 양은 자유롭게 바꾼다'],'0','소금과 설탕이라는 종류만 바꾸고 다른 조건을 같게 비교합니다.')};}
   const strength=(s.amount==='more'?2:1)/(s.water==='more'?2:1),higher=strength>1,lower=strength<1;return{svg:jar(65,125,'#b9deed')+jar(285,125,'#b9deed')+ellipse(120,130,23,32,'#f2d6a4')+ellipse(340,higher?112:lower?166:130,23,32,'#f2d6a4')+label('기준 설탕물',120,35)+label('비교 설탕물',340,35)+label(higher?'더 높이 뜸':lower?'더 아래에 놓임':'뜨는 정도 같음',340,280),text:higher?'물의 양은 같고 녹인 설탕의 양이 더 많으면 더 진합니다. 같은 물체가 더 높이 뜨는 모습을 비교할 수 있습니다.':lower?'녹인 설탕의 양은 같고 물을 더 넣으면 묽어집니다. 같은 물체가 덜 뜨는 모습을 비교할 수 있습니다.':'설탕과 물의 비율이 같으면 진하기가 같습니다. 전체 용액의 양이 많다는 이유만으로 더 진한 것은 아닙니다.',note:'두 용액의 온도와 물체는 같고 설탕은 모두 녹은 조건입니다. 오른쪽의 ‘더 많음’은 각각 두 배인 모형입니다. 같은 용기에 일부씩 덜어 높이를 같게 한 비교 그림이며, 실제 뜨는 높이의 수치·밀도 공식은 다루지 않습니다.',check:check('같은 양의 물에 설탕을 더 녹이면?',['더 진해진다','언제나 더 묽어진다','물의 양만 진하기에 영향을 준다'],'0','용질인 설탕을 더 녹이면 진해지고, 같은 설탕물에 물을 더하면 묽어집니다.')};}
 });
 add('acid-base',{
  title:'산·염기와 물질의 반응',codes:['6과09-02'],initial:{material:'shell',stage:'before'},
  fields:[field('material','같은 크기의 물질',[['shell','달걀 껍데기'],['protein','익힌 흰자']]),stages],
  view(s){const after=s.stage==='after',shell=s.material==='shell';let svg=jar(65,135,'#cee5ed')+jar(285,135,'#cee5ed')+label('묽은 염산',120,35)+label('묽은 수산화 나트륨',340,35);
   svg+=ellipse(120,205,shell&&after?14:30,12,'#f7eee0')+ellipse(340,205,!shell&&after?14:30,12,'#f7eee0');
   if(after&&shell)for(let i=0;i<8;i++)svg+=circle(100+(i%3)*18,105+Math.floor(i/3)*27,4,'#88b9ce');
   if(after&&!shell)for(let i=0;i<5;i++)svg+=circle(310+i*13,195-(i%2)*20,4,'#faf6eb');
   return{svg,text:after?(shell?'탄산 칼슘이 들어 있는 달걀 껍데기는 산성 용액에서 기포가 생기고 점차 줄어듭니다. 비교한 염기성 용액에서는 같은 시간 동안 뚜렷한 변화가 거의 없습니다.':'단백질이 들어 있는 익힌 흰자는 염기성 용액에서 표면이 변하고 점차 풀어지는 모습을 비교할 수 있습니다. 산성 용액과의 차이를 관찰합니다.'):'같은 크기의 물질과 같은 양의 용액을 준비하고, 처음 모습을 기록합니다. 용액의 종류만 바꾸어 일정 시간이 지난 뒤와 비교합니다.',note:'교사가 준비한 시약·표본의 관찰을 단순화한 모형입니다. 반응 시간·정도는 농도와 조건에 따라 다릅니다. 모든 산·염기에서 즉시 같은 변화가 생긴다는 뜻이 아닙니다. 보안경·장갑과 교사 지도가 필요하며, 만지거나 맛보지 않습니다.',check:shell?check('달걀 껍데기에서 기포가 생긴 관찰이 보여 주는 성질은?',['산성 용액이 탄산 칼슘과 반응함','산성 용액이 모든 물질을 녹임','염기성 용액에서만 기포가 생김'],'0','성취기준에서 다루는 산성 용액의 성질은 탄산 칼슘과 반응하는 것입니다.'):check('익힌 흰자를 비교하는 까닭은?',['단백질에 대한 용액의 성질을 관찰하려고','용액의 맛을 확인하려고','용액의 색만으로 진하기를 계산하려고'],'0','염기성 용액이 단백질과 반응하는 성질을 관찰합니다.')};}
 });
 add('state-change',{
  title:'증발·끓음·차가운 컵의 응결',codes:['4과10-02'],initial:{kind:'evaporation',stage:'before'},
  fields:[field('kind','관찰할 변화',[['evaporation','증발'],['boiling','끓음'],['condensation','컵 바깥의 물방울']]),stages],
  view(s){const after=s.stage==='after',boil=s.kind==='boiling',dew=s.kind==='condensation';let svg=jar(175,after&&!dew?105:140,'#add9ed');if(dew)svg+=rect(195,95,30,30,'#e9f6ff')+rect(235,115,30,30,'#e9f6ff');
   if(after&&boil)for(let i=0;i<9;i++)svg+=circle(195+(i%3)*30,135+Math.floor(i/3)*25,5,'#f4fcff');
   if(after&&dew)for(let i=0;i<10;i++)svg+=circle(i%2?290:165,100+Math.floor(i/2)*27,5,'#6daed1');
   svg+=label(dew?'색 물과 얼음이 든 컵':boil?'가열하여 끓이는 물':'상온에서 가만히 둔 물',230,35)+label(after?'변화 뒤':'처음',230,275);
   return{svg,text:!after?'물의 높이와 컵 안팎의 모습을 먼저 기록합니다. 시간이 지난 뒤와 비교합니다.':dew?'컵 바깥에 물방울이 맺힙니다. 공기 중의 수증기가 차가운 컵 표면에서 물로 변한 응결입니다. 컵 안의 색 물이 새어 나온 것이 아닙니다.':boil?'물속에서도 기포가 생기며 물이 수증기로 변합니다. 물의 양이 줄어듭니다. 끓음과 증발은 모두 물이 수증기로 변하는 현상입니다.':'끓지 않아도 물 표면에서 물이 수증기로 변하여 양이 줄어듭니다. 수증기는 눈에 보이지 않습니다.',note:'컵 바깥은 처음에 마른 조건이고, 맺힌 물방울은 무색입니다. 높이·변화 시간은 모형이며 비교용입니다. 가열 실험은 교사 지도 아래 수행합니다. 흰 김과 눈에 보이지 않는 수증기를 구별합니다.',check:dew?check('컵 바깥 물방울의 주된 출처는?',['공기 중 수증기','컵을 통과한 색 물','얼음 자체가 컵을 통과함'],'0','공기 중 수증기가 차가운 컵 표면에서 응결합니다.'):check('증발과 끓음의 공통점은?',['물이 수증기로 변한다','항상 물속에서 기포가 생긴다','반드시 끓는 온도여야 한다'],'0','끓지 않아도 증발은 일어납니다. 두 현상 모두 물이 수증기로 변합니다.')};}
 });
 add('light-shadow',{
  title:'렌즈를 지나는 빛과 물체 보기',codes:['6과02-01','6과02-02'],initial:{kind:'lens',setting:'convex'},
  fields:s=>[field('kind','관찰 실험',[['lens','렌즈의 굴절'],['box','어둠상자 속 물체']]),field('setting','조건',s.kind==='lens'?[['none','렌즈 없음'],['convex','볼록 렌즈'],['concave','오목 렌즈']]:[['dark','빛이 들어오지 않음'],['lit','빛이 들어옴']])],
  view(s){if(s.kind==='box'){const lit=s.setting==='lit';return{svg:rect(50,55,320,200,'#243743')+(lit?circle(80,90,15,'#f6cf6e')+rect(210,150,45,45,'#eea272')+line(90,95,230,150,'#f5cc69',3)+line(245,160,410,120,'#f5cc69',3):'')+ellipse(420,120,18,10,'#c4ddd8')+label(lit?'물체에서 온 빛이 눈에 들어옴':'물체가 있어도 보이지 않음',230,285),text:lit?'광원에서 나온 빛이 물체에 닿고, 물체에서 반사된 빛이 눈에 들어와 물체를 볼 수 있습니다.':'빛이 물체에 닿지 않으면 물체에서 반사된 빛도 눈에 들어오지 않아 물체가 보이지 않습니다. 눈에서 빛이 나가서 보는 것이 아닙니다.',note:schematic+' 눈으로 레이저나 강한 광원을 직접 바라보지 않습니다.',check:check('광원이 아닌 물체를 보는 과정은?',['광원 → 물체 → 눈','눈 → 물체 → 광원','물체가 없어도 눈에서 빛이 나감'],'0','물체에서 반사된 빛이 눈에 들어옵니다.')};}
   let svg='';if(s.setting==='convex')svg+=ellipse(220,150,22,100,'#bdddea');if(s.setting==='concave')svg+='<path d="M195 50 Q225 150 195 250 L245 250 Q215 150 245 50 Z" fill="#bdddea"/>';
   for(const y of [95,150,205]){svg+=line(35,y,220,y,'#d79c22',3);const end=s.setting==='convex'?150:s.setting==='concave'?150+(y-150)*1.8:y;svg+=line(220,y,405,end,'#d79c22',3);}
   return{svg:svg+label('평행하게 들어오는 빛',130,285),text:s.setting==='convex'?'볼록 렌즈를 지난 빛은 가운데 쪽으로 꺾여 모이는 모습을 볼 수 있습니다.':s.setting==='concave'?'오목 렌즈를 지난 빛은 바깥쪽으로 꺾여 퍼지는 모습을 볼 수 있습니다.':'렌즈가 없으면 같은 공기 속에서 빛이 곧게 나아갑니다.',note:'렌즈 안팎에서 굴절하는 빛의 전체 경향을 단순화한 그림입니다. 초등에서는 각도·초점 거리 계산이나 물체 거리별 상의 비교를 평가하지 않습니다. 햇빛을 모아 보거나 눈으로 광선을 바라보지 않습니다.',check:check('빛이 렌즈를 지나며 꺾이는 현상은?',['굴절','용해','응결'],'0','서로 다른 물질의 경계를 지날 때 빛이 꺾여 나아가는 현상을 굴절이라고 합니다.')};}
 });
 add('refraction',{
  title:'여러 거울·렌즈의 상 비교',codes:['9과10-02'],initial:{optic:'plane',distance:'near'},
  fields:[field('optic','거울 또는 렌즈',[['plane','평면거울'],['convexMirror','볼록거울'],['concaveMirror','오목거울'],['convexLens','볼록렌즈'],['concaveLens','오목렌즈']]),field('distance','물체 위치의 두 예',[['near','아주 가까운 물체'],['far','충분히 먼 물체']])],
  view(s){const converging=['concaveMirror','convexLens'].includes(s.optic),inverted=converging&&s.distance==='far',large=converging&&!inverted,small=['convexMirror','concaveLens'].includes(s.optic)||inverted,scale=large?1.5:small?.65:1;
   const arrow=(x,scale,color)=>`<g transform="translate(${x} 160) scale(${scale} ${inverted&&x===335?-scale:scale})">${line(0,40,0,-40,color,8)}<path d="M-16 -22 L0 -45 L16 -22" fill="none" stroke="${color}" stroke-width="8"/></g>`;
   return{svg:arrow(110,1,'#d8853c')+arrow(335,scale,'#3c8e99')+label('물체',110,275)+label('관찰되는 상',335,275)+line(230,40,230,260,'#c3d2d8',2),text:(s.optic==='plane'?'평면거울에서는 물체와 크기가 같고 바로 선 상이 보입니다.':large?'이 예처럼 아주 가까이 두면 물체보다 크고 바로 선 상이 보입니다.':inverted?'이 예처럼 충분히 멀리 두면 작고 거꾸로 된 상을 얻습니다. 가까운 경우와 방향이 달라집니다.':'물체보다 작고 바로 선 상이 보입니다.')+' 그림은 물체와 상의 방향·크기 비교이며 실제 상의 위치를 나타내지 않습니다.',note:'오목거울·볼록렌즈의 ‘충분히 먼’ 예는 작고 거꾸로 보이는 조건을 골랐습니다. 모든 거리에서 상이 작다는 뜻은 아닙니다. 상의 위치·배율 계산, 실상/허상 분류는 중학교 시험 범위로 제시하지 않습니다.',check:check('물체를 아주 가까이 둘 때 크고 바로 선 상을 볼 수 있는 조합은?',['오목거울과 볼록렌즈','볼록거울과 오목렌즈','평면거울만'],'0','오목거울과 볼록렌즈는 가까운 물체를 확대하여 바로 선 상으로 볼 수 있습니다.')};}
 });
 add('weight-compare',{
  title:'고체·액체·기체의 모양과 공간',codes:['4과05-02'],initial:{kind:'liquid',container:'narrow',stage:'before'},
  fields:s=>[field('kind','관찰할 물질',[['solid','나무 도막'],['liquid','물'],['gas','컵 속 공기']]),...(s.kind==='gas'?[stages]:[field('container','담는 용기',[['narrow','좁은 용기'],['wide','넓은 용기']])])],
  view(s){if(s.kind==='gas'){const after=s.stage==='after';return{svg:rect(65,105,330,150,'#b6dbed')+'<path d="M175 220 L175 70 L285 70 L285 220" fill="#f0f7fa" stroke="#64748b" stroke-width="5"/>'+rect(180,after?166:211,100,after?54:9,'#b6dbed')+label(after?'컵을 기울여 공기를 뺀 뒤':'거꾸로 세워 넣은 컵',230,35)+(after?circle(310,125,7,'#f4f9fc')+circle(330,98,5,'#f4f9fc'):label('공기',230,140)),text:after?'컵을 기울여 공기를 빼면 그 자리에 물이 들어갑니다. 공기가 차지하던 공간이 있었음을 알 수 있습니다.':'공기가 든 컵을 거꾸로 물속에 똑바로 넣으면 공기가 공간을 차지하여 물이 컵 안을 모두 채우지 못합니다.',note:'공기가 기포로 빠져나간 뒤 컵을 다시 세운 모습을 비교한 모형입니다. 유리 대신 안전한 투명 용기를 사용하며 실제 물의 높이는 조건에 따라 다릅니다.',check:check('공기를 빼자 컵 안으로 물이 들어간 까닭은?',['공기가 공간을 차지하고 있었기 때문','공기는 무조건 눈에 보이기 때문','공기는 물질이 아니기 때문'],'0','기체도 공간을 차지합니다.')};}
   const wide=s.container==='wide',w=wide?220:110,x=230-w/2,solid=s.kind==='solid';return{svg:rect(x,60,w,180,'#eef5f8')+(solid?rect(205,200,50,35,'#a77d58'):rect(x+5,wide?180:120,w-10,wide?55:115,'#8cc5e3'))+line(x,60,x,240)+line(x,240,x+w,240)+line(x+w,240,x+w,60)+label(solid?'나무 도막의 모양과 부피는 같음':'물의 모양은 달라져도 부피는 같음',230,280),text:solid?'고체인 나무 도막은 다른 용기에 옮겨도 모양과 부피가 일정합니다.':'액체인 물은 용기에 따라 모양이 달라지지만 흘리거나 증발하지 않으면 부피는 같습니다. 높이가 낮아졌다고 양이 줄어든 것은 아닙니다.',note:'같은 물질을 흘리지 않고 옮긴 비교 그림입니다. 높이는 설명용이며 입자나 상태 변화의 까닭은 다루지 않습니다.',check:check('물을 넓은 용기로 옮겨 물 높이가 낮아졌을 때 옳은 설명은?',['모양은 달라져도 부피는 같다','물이 반드시 사라졌다','액체는 항상 모양이 같다'],'0','액체는 담긴 용기의 모양을 따르지만 같은 양을 옮기면 부피가 같습니다.')};}
 });
 add('volcano-model',{
  title:'현무암과 화강암 관찰·분류',codes:['4과11-03'],initial:{rock:'basalt',detail:'whole'},
  fields:[field('rock','관찰할 암석',[['basalt','현무암'],['granite','화강암']]),field('detail','관찰 초점',[['whole','전체 모습'],['grain','알갱이와 표면']])],
  view(s){const basalt=s.rock==='basalt';let svg=ellipse(230,155,155,95,basalt?'#535b5e':'#d6c6b5');for(let i=0;i<38;i++){const x=115+(i*47)%230,y=95+(i*31)%125;if(basalt){if(i<10)svg+=ellipse(x,y,6,4,'#333d42');}else svg+=rect(x,y,(s.detail==='grain'?15:9)+(i%4)*2,s.detail==='grain'?15:9,['#eee6d9','#bdac98','#68716e'][i%3]);}return{svg:svg+label(basalt?'어두운 색·작은 알갱이':'밝은 바탕·눈에 보이는 여러 알갱이',230,280),text:basalt?'이 현무암 표본은 색이 어둡고 알갱이가 매우 작아 하나하나 구별하기 어렵습니다. 구멍이 보이는 표본도 있지만 모든 현무암에 구멍이 있는 것은 아닙니다.':'이 화강암 표본은 밝은 바탕에 여러 색의 알갱이가 눈에 보입니다. 색뿐 아니라 알갱이의 크기와 표면의 특징을 함께 관찰하여 분류합니다.',note:schematic+' 모든 암석의 색과 모습이 완전히 같지는 않습니다. 실제 표본을 돋보기로 관찰한 기록과 함께 비교합니다.',check:check('화강암과 현무암을 비교할 때 함께 살펴볼 것은?',['색과 알갱이의 크기·표면','표본 이름만','무조건 구멍의 개수만'],'0','여러 관찰 특징을 함께 사용합니다. 현무암에 반드시 구멍이 있는 것은 아닙니다.')};}
 });
 add('lever-balance',{
  title:'물체를 밀고 당길 때',codes:['4과01-01'],initial:{direction:'push',stage:'before'},fields:[field('direction','가하는 힘',[['push','밀기'],['pull','당기기']]),stages],
  view(s){const after=s.stage==='after',push=s.direction==='push',x=after?(push?300:90):195;return{svg:line(40,235,420,235,'#657a83',5)+rect(x,160,70,70,'#cba57f')+label(after?(push?'→':'←'):'힘을 가하기 전',230,115,'#246874',35)+label('같은 바닥 위의 상자',230,285),text:after?'물체를 밀거나 당기면 움직이기 시작하거나 움직이는 방향이 달라질 수 있습니다. 힘의 방향을 바꾸어 결과를 비교합니다.':'멈춰 있는 상자의 위치를 기록합니다. 밀거나 당길 방향을 정한 뒤 변화를 관찰합니다.',note:'같은 상자에 움직이기에 충분한 힘을 가하는 모형입니다. 이동 거리는 실제 측정값이 아니며 힘과 거리의 비례를 뜻하지 않습니다.',check:check('힘을 가한 뒤 확인할 관찰 결과는?',['물체의 움직임과 방향','상자 이름만','항상 같은 거리인지 미리 단정'],'0','힘을 가하기 전후의 움직임을 비교합니다.')};}
 });
 add('seasons',{
  title:'하루의 천체 위치·낮밤·계절 별자리',codes:['6과12-01','6과12-02','6과12-03'],initial:{kind:'daily',time:'morning',season:'spring',side:'day'},
  fields:s=>[field('kind','관찰할 주제',[['daily','하루 동안 위치'],['daynight','낮과 밤 모형'],['annual','계절별 밤하늘']]),s.kind==='daily'?field('time','관찰 시각',[['morning','아침'],['noon','한낮'],['evening','저녁'],['star1','별 관찰 첫 시각'],['star2','별 관찰 몇 시간 뒤']]):s.kind==='annual'?field('season','계절',[['spring','봄'],['summer','여름'],['autumn','가을'],['winter','겨울']]):field('side','관찰 지점',[['day','태양을 향한 쪽'],['night','태양의 반대쪽']])],
  view(s){if(s.kind==='daynight'){const day=s.side==='day';return{svg:circle(60,145,32,'#f7ca5f')+line(100,145,190,145,'#e3b54d',3)+circle(275,145,75,'#344b68')+'<path d="M275 70 A75 75 0 0 0 275 220 Z" fill="#8dbcd2"/>'+circle(day?215:335,145,7,'#ed684b')+label(day?'관찰 지점: 낮':'관찰 지점: 밤',275,275),text:day?'태양빛을 받는 쪽은 낮입니다. 지구가 자전하면서 한 지점이 빛을 받는 쪽과 받지 않는 쪽을 번갈아 지나갑니다.':'태양빛을 받지 않는 쪽은 밤입니다. 태양이 지구 주위를 하루에 한 바퀴 도는 것이 아니라 지구의 자전으로 낮과 밤이 생깁니다.',note:'지구의 크기와 태양까지 거리는 실제 비율이 아닙니다. 기존 태양 고도 실험과 함께 비교합니다.',check:check('낮과 밤이 반복되는 주된 까닭은?',['지구의 자전','하루마다 지구가 공전 한 바퀴','태양이 매일 꺼지기 때문'],'0','지구의 자전 때문에 태양빛을 받는 쪽이 바뀝니다.')};}
   if(s.kind==='annual'){const names={spring:'사자자리',summer:'백조자리',autumn:'페가수스자리',winter:'오리온자리'},points={spring:[[120,180],[175,150],[230,175],[285,110],[320,150],[280,185]],summer:[[230,55],[230,120],[230,185],[230,240],[145,145],[315,145]],autumn:[[155,85],[295,85],[295,220],[155,220]],winter:[[155,65],[295,65],[155,240],[295,240],[200,150],[225,145],[250,140]]},p=points[s.season];let svg=rect(35,30,390,230,'#23384f');for(const [x,y]of p)svg+=circle(x,y,4,'#f6edcb');return{svg:svg+label(names[s.season]+' · 모양을 단순화한 그림',230,288),text:'우리나라에서 '+{spring:'봄',summer:'여름',autumn:'가을',winter:'겨울'}[s.season]+' 저녁에 관찰하기 좋은 대표 별자리의 예는 '+names[s.season]+'입니다. 같은 장소·비슷한 저녁 시각에 비교하면 계절에 따라 보이는 별자리가 달라집니다. 지구가 공전하여 밤에 바라보는 우주 방향이 달라지기 때문입니다.',note:'계절별 대표 예를 비교하는 설명 그림이며 실제 천체 관측 프로그램이나 정확한 관측 날짜·좌표가 아닙니다. 특정 계절에만 절대적으로 보인다는 뜻도 아닙니다.',check:check('같은 장소·같은 저녁 시각에 계절별 별자리가 달라지는 까닭은?',['지구가 공전하여 밤에 보는 방향이 달라져서','별자리가 하루마다 모두 없어져서','지구가 자전하지 않아서'],'0','지구의 공전으로 계절에 따라 밤에 바라보는 방향이 달라집니다.')};}
   const positions={morning:[90,190],noon:[230,60],evening:[370,190],star1:[170,110],star2:[280,120]},p=positions[s.time],star=s.time.startsWith('star');return{svg:rect(35,30,390,220,star?'#23384f':'#d9edf5')+line(40,240,420,240)+circle(p[0],p[1],star?6:22,star?'#fff1bb':'#f2bf50')+label('동쪽',65,280)+label('남쪽 하늘',230,280)+label('서쪽',395,280),text:star?'남쪽 하늘의 같은 별을 몇 시간 간격으로 비교하면 대체로 동쪽에서 서쪽으로 이동해 보입니다. 북극성 주변 별들은 북극성을 중심으로 도는 모습으로 관찰합니다.':'태양은 아침에 동쪽, 한낮에는 남쪽 높은 하늘, 저녁에는 서쪽에서 보입니다. 같은 장소에서 하루 동안 위치의 규칙성을 기록합니다.',note:'우리나라에서 남쪽을 바라본 대표적인 경로의 모형이며 날짜별 실제 방위각·고도가 아닙니다. 태양을 맨눈이나 렌즈로 직접 보지 않습니다.',check:check('우리나라에서 하루 동안 태양이 이동해 보이는 대체적인 방향은?',['동쪽 → 남쪽 하늘 → 서쪽','서쪽 → 남쪽 하늘 → 동쪽','항상 북쪽 한자리에 있음'],'0','지구의 자전으로 태양이 동쪽에서 서쪽으로 이동해 보입니다.')};}
 });
 add('diffusion',{
  title:'입자·상태 변화·기체 조건 비교',codes:['9과04-02','9과04-03','9과04-04','9과06-01','9과06-02','9과06-03'],initial:{kind:'phase',phase:'solid',gas:'pressure',setting:'normal',step:'0'},
  fields:s=>[field('kind','실험',[['phase','상태 변화와 입자'],['curve','순수한 물의 가열'],['gas','기체의 압력·온도와 부피']]),...(s.kind==='phase'?[field('phase','상태',[['solid','고체'],['liquid','액체'],['gas','기체']])]:s.kind==='curve'?[field('step','같은 세기로 가열한 순서',[['0','얼음 가열'],['1','녹는 동안'],['2','물 가열'],['3','끓는 동안']])]:[field('gas','바꾸는 변인',[['pressure','온도 일정: 바깥 압력'],['temperature','압력 일정: 온도']]),field('setting','조건',[['low','낮음'],['normal','중간'],['high','높음']])])],
  view(s){if(s.kind==='phase'){const gas=s.phase==='gas',solid=s.phase==='solid';let svg=rect(65,40,330,215,'#edf4f7');for(let i=0;i<20;i++){const x=gas?85+(i*67)%285:125+(i%5)*40+(solid?0:(i%2)*8),y=gas?60+(i*41)%170:solid?95+Math.floor(i/5)*37:130+Math.floor(i/5)*27;svg+=circle(x,y,7,'#508f9c');if(gas)svg+=line(x+9,y,x+17,y,'#c48b47',2);}return{svg:svg+label('입자 수·종류·크기는 같음',230,287),text:solid?'고체의 입자는 서로 가까이 규칙적으로 배열되어 제자리에서 진동합니다. 고체의 입자가 멈춰 있는 것은 아닙니다.':gas?'기체의 입자는 서로 멀리 떨어져 자유롭게 운동합니다. 상태가 바뀌어도 입자 자체의 크기가 커지거나 새로운 입자로 바뀌는 것은 아닙니다.':'액체의 입자는 가까이 있지만 불규칙하게 배열되어 서로 자리를 바꾸며 운동합니다. 상태가 변해도 밖으로 새지 않았다면 질량은 보존됩니다.',note:'같은 물질의 입자 배열을 비교한 정지 모형입니다. 고체→액체에서 부피가 항상 증가한다는 뜻이 아닙니다. 물은 얼 때 부피가 증가하는 예외를 함께 기억합니다.',check:check('상태 변화에서 변하지 않는 것은?',['입자 자체의 종류와 크기','입자 사이 거리와 배열','전체 물질의 모양'],'0','입자 자체가 커지는 것이 아니라 배열·거리·운동 상태가 달라집니다.')};}
   if(s.kind==='curve'){const pts=[[70,240],[140,190],[220,190],[300,80],[385,80]],i=+s.step;let svg=line(55,260,415,260)+line(55,260,55,35);for(let j=0;j<4;j++)svg+=line(...pts[j],...pts[j+1],j===i?'#dc8a30':'#80a8b3',5);svg+=label('가열 시간 →',250,292)+label('0 ℃',28,195,'#173f50',12)+label('100 ℃',28,85,'#173f50',12);return{svg,text:['얼음의 온도가 올라갑니다.','얼음과 물이 함께 있는 동안 공급한 열은 녹는 데 쓰여 온도가 일정하게 유지됩니다.','모두 녹은 물의 온도가 올라갑니다.','물이 끓는 동안 공급한 열은 기화에 쓰여 온도가 일정하게 유지됩니다.'][i],note:'1기압에서 순수한 물을 가열한 이상적인 곡선입니다. 구간 길이는 실제 소요 시간이나 필요한 열량의 비율이 아닙니다. 실제 측정값은 장치·불순물·압력에 따라 달라집니다.',check:check('순수한 물이 끓는 동안 계속 열을 공급하면?',['열이 상태 변화에 쓰이며 온도가 일정할 수 있다','열 공급이 무조건 멈춘다','입자 자체가 커진다'],'0','가열 중에도 상태 변화가 일어나는 동안 온도가 일정한 구간이 있습니다.')};}
   const thermal=s.gas==='temperature',order={low:0,normal:1,high:2}[s.setting],height=thermal?[90,130,170][order]:[170,130,90][order],top=235-height;let svg=rect(145,45,170,195,'#edf4f7')+rect(150,top,160,8,'#607c88');for(let i=0;i<15;i++){const x=165+(i*43)%130,y=top+24+(i*29)%(height-35);svg+=circle(x,y,4,'#4d91a0')+line(x+6,y,x+(thermal?8+order*5:13),y,'#c48b47',2);}return{svg:svg+label(thermal?'압력 일정 · 온도 '+{low:'낮음',normal:'중간',high:'높음'}[s.setting]:'온도 일정 · 바깥 압력 '+{low:'낮음',normal:'중간',high:'높음'}[s.setting],230,285),text:thermal?'같은 양의 기체를 압력이 일정하게 유지되도록 하면 온도가 높을수록 입자 운동이 활발해지고 부피가 커집니다. 온도가 낮으면 부피가 작아집니다.':'같은 양의 기체에서 온도가 일정할 때 바깥 압력을 높이면 부피가 작아집니다. 입자 사이의 거리가 줄어들지만 입자 자체가 작아지지는 않습니다.',note:'새지 않는 기체와 마찰 없이 움직이는 피스톤의 정성 모형입니다. 입자 수는 같습니다. 화살표는 운동의 경향이며 실제 속도·부피 수치가 아닙니다. 기체 법칙 수식 계산은 여기서 평가하지 않습니다.',check:thermal?check('온도와 부피의 관계를 비교할 때 일정하게 할 것은?',['기체의 양과 압력','기체의 온도만','기체의 양은 마음대로 바꾼다'],'0','온도만 바꾸어 비교하려면 기체의 양과 압력을 일정하게 합니다.'):check('온도가 일정할 때 기체를 더 압축하면?',['입자 사이 거리가 줄어든다','입자 자체가 작아진다','입자 수가 저절로 줄어든다'],'0','같은 수의 입자가 더 좁은 공간에 있게 됩니다.')};}
 });
 add('weather-front',{
  title:'공기의 팽창과 구름 생성',codes:['9과17-03'],initial:{moisture:'moist',stage:'before'},
  fields:[field('moisture','공기의 수증기 조건',[['moist','수증기가 충분함'],['dry','매우 건조함']]),field('stage','부피 변화',[['before','팽창 전'],['after','빠르게 팽창시킨 뒤'],['compress','다시 압축한 뒤']])],
  view(s){const expanded=s.stage==='after',cloud=expanded&&s.moisture==='moist',h=expanded?170:100;let svg=rect(100,50,260,195,'#e4eff4')+rect(105,235-h,250,8,'#708b99');if(cloud)for(let i=0;i<35;i++)svg+=circle(125+(i*41)%210,105+(i*23)%115,5,'#fff');return{svg:svg+label(expanded?'부피 증가 · 온도 하강':'작은 부피 · 비교적 높은 온도',230,285),text:expanded?(cloud?'빠르게 팽창한 공기의 온도가 내려가고 상대습도가 높아집니다. 충분히 냉각되어 이슬점에 도달하면 수증기가 작은 물방울로 응결하여 구름처럼 뿌옇게 보입니다.':'팽창하면 온도가 내려가지만, 이 모형처럼 수증기가 매우 적어 이슬점까지 냉각되지 않으면 눈에 보이는 구름이 생기지 않습니다.'):s.stage==='compress'?'다시 압축하면 공기의 온도가 올라가고 작은 물방울이 증발하여 뿌연 모습이 사라질 수 있습니다.':'수증기가 포함된 공기의 처음 부피·온도와 맑은 정도를 기록합니다. 수증기 자체는 눈에 보이지 않습니다.',note:'외부와 열 교환이 거의 없는 빠른 팽창과 응결핵이 있는 조건의 모형입니다. 실제 센서 측정값이 아닙니다. 압력 용기를 직접 가압하거나 불을 사용하라는 지시가 아닙니다.',check:check('공기가 상승하면서 구름이 생기는 과정은?',['팽창 → 온도 하강 → 수증기 응결','팽창 → 온도 상승 → 수증기 자체가 보임','압축 → 온도 상승만으로 항상 구름'],'0','상승한 공기가 팽창해 냉각되고 이슬점에 도달하면 응결하여 구름이 생깁니다.')};}
 });
 add('motion-energy',{
  title:'자유 낙하의 시간·속력·에너지',codes:['9과19-01','9과19-02','9과19-03','9과19-04'],initial:{mass:'1',time:'0'},
  fields:[field('mass','물체 질량',[['1','1 kg'],['2','2 kg']]),field('time','놓은 뒤 시간',[['0','0 s'],['1','1 s'],['2','2 s'],['3','3 s']])],
  view(s){const t=+s.time,m=+s.mass,y=60+4.9*t*t*3.8,speed=9.8*t,kin=.5*m*speed*speed,total=m*9.8*50,pot=total-kin;let svg=line(85,45,85,255)+line(85,255,415,255)+line(85,255,390,50,'#4d96a4',3)+circle(85+t*101.67,255-t*68.33,6,'#dc8e38')+circle(40,y,9,'#668ec0')+label('시간 →',260,290)+label('속력',95,30)+label(speed.toFixed(1)+' m/s',325,35)+label('공: 낙하 위치',60,280,'#173f50',11);return{svg,text:`속력은 ${speed.toFixed(1)} m/s입니다. 같은 1초마다 9.8 m/s씩 증가합니다. 위치 에너지 ${pot.toFixed(1)} J, 운동 에너지 ${kin.toFixed(1)} J, 합 ${total.toFixed(1)} J입니다. 질량이 달라도 같은 시간의 속력은 같지만 에너지의 크기는 질량에 따라 달라집니다.`,note:'공기 저항을 무시하고 높이 50 m에서 정지 상태로 놓은 이론 모형입니다. 중력 가속도는 9.8 m/s²이며 그래프는 속력-시간입니다. 실제 촬영·측정 자료가 아닙니다.',check:check('공기 저항이 없을 때 질량이 다른 두 물체를 동시에 놓으면?',['같은 시간이 지난 뒤 속력이 같다','무거운 물체의 속력이 반드시 두 배다','가벼운 물체만 속력이 증가한다'],'0','자유 낙하에서 속력의 시간에 따른 증가율은 질량과 무관합니다.')};}
 });
 add('ohms-law',{
  title:'정전기와 코일의 자기장',codes:['9과14-01','9과14-04'],initial:{kind:'coil',current:'forward',strength:'weak',pole:'N',stage:'before'},
  fields:s=>[field('kind','관찰 실험',[['coil','코일과 자석'],['static','정전기 유도'],['rub','마찰 전기']]),...(s.kind==='coil'?[field('current','전류 방향',[['off','전류 없음'],['forward','방향 1'],['reverse','방향 반대']]),field('strength','전류 세기',[['weak','약함'],['strong','강함']]),field('pole','마주 보는 자석의 극',[['N','N극'],['S','S극']])]:[stages])],
  view(s){if(s.kind==='rub'){const after=s.stage==='after';let svg=rect(50,80,150,130,'#decce8')+rect(265,80,150,130,'#d9dec1');for(let i=0;i<4;i++){svg+=label('+',75+i*32,120,'#ba5752',22)+label('+',288+i*32,120,'#ba5752',22);}for(let i=0;i<(after?6:4);i++)svg+=label('−',70+(i%4)*32,165+Math.floor(i/4)*25,'#426eac',22);for(let i=0;i<(after?2:4);i++)svg+=label('−',288+i*32,165,'#426eac',22);return{svg:svg+label('플라스틱 막대',125,265)+label('천',340,265),text:after?'이 모형에서는 마찰할 때 천에서 막대로 전자가 이동했습니다. 막대는 음전하, 천은 양전하를 띠며 두 물체를 합한 전체 전하량은 보존됩니다.':'처음에는 두 물체 모두 양전하와 음전하의 양이 같아 전체적으로 중성입니다. 마찰 전후 전자 분포를 비교합니다.',note:'전자가 천에서 막대로 이동하는 조합의 모형입니다. 양성자가 이동하거나 전하가 새로 생기는 것이 아닙니다. 표시 개수는 실제 입자 수가 아닙니다.',check:check('마찰 전기가 생길 때 주로 이동하는 것은?',['전자','양성자','원자핵 전체'],'0','물체 사이에 전자가 이동하여 한쪽은 음전하, 다른 쪽은 양전하를 띱니다.')};}if(s.kind==='static'){const after=s.stage==='after';let svg=rect(40,95,75,110,'#b990cb')+ellipse(275,150,100,70,'#c5dde6');for(let i=0;i<4;i++){svg+=label('−',70,113+i*24,'#5b3777',22);svg+=label('+',225+i*28,105,'#c64b49',22);svg+=label('−',after?325:225+i*28,after?145+i*17:180,'#437ec1',22);}return{svg:svg+label(after?'음전하 막대를 가까이 둠':'중성 금속 도체',230,280),text:after?'음전하를 띤 막대를 접촉하지 않고 가까이하면 금속 도체의 전자가 밀려나 먼 쪽으로 이동합니다. 가까운 쪽은 양전하, 먼 쪽은 음전하를 띤 부분이 생깁니다. 도체 전체의 전하량은 변하지 않습니다.':'금속 도체 전체는 전기적으로 중성입니다. 외부의 대전체를 가까이하기 전후의 전하 분포를 비교합니다.',note:'분리되어 있고 접지되지 않은 금속 도체의 정전기 유도 모형입니다. 양전하가 도체 안을 이동한 것이 아니라 전자의 분포가 달라진 것입니다. 표시 개수는 실제 원자 수가 아닙니다.',check:check('접지하지 않은 도체에 대전체를 가까이할 때 달라지는 것은?',['전자의 분포','양성자의 위치가 반대편으로 이동','도체 전체 전하가 반드시 늘어남'],'0','정전기 유도에서는 전자가 재배치됩니다. 접촉·접지가 없으면 도체 전체 전하량은 보존됩니다.')};}
   const on=s.current!=='off',north=s.current==='forward',repel=(north?'N':'S')===s.pole;let svg='';for(let i=0;i<8;i++)svg+=ellipse(110+i*20,150,13,50,'none').replace('/>',' stroke="#b7874b" stroke-width="4"/>');svg+=rect(335,115,70,70,s.pole==='N'?'#dc7774':'#6d99cf')+label(s.pole,370,158,'#fff',25)+label(on?(north?'N':'S'):'전류 없음',285,154)+label(on?(repel?'← →':'→ ←'):'힘 변화 없음',230,45,'#276975',27);if(on){svg+=label(north?'자기장 →':'← 자기장',175,240);if(s.strength==='strong')svg+=line(100,260,260,260,'#3e9094',6);}return{svg,text:on?`전류의 방향을 바꾸면 코일의 자기장 방향과 양 끝의 극이 바뀝니다. 마주 보는 극이 ${repel?'같아 서로 밀어냅니다':'달라 서로 끌어당깁니다'}. 전류가 강할수록 코일의 자기장이 강해집니다.`:'전류가 흐르지 않는 공심 코일에는 전류에 의한 자기장이 생기지 않습니다. 전류를 흘린 조건과 비교합니다.',note:'코일 내부 자기장 방향을 표시한 정성 모형입니다. 전동기는 자기장 속 전류가 흐르는 코일이 힘을 받아 회전하는 원리를 이용합니다. 이 그림의 두 끝 극 비교는 전동기 전체 구조·회전 과정을 대신하지 않습니다.',check:check('코일의 전류 방향을 반대로 바꾸면?',['자기장 방향과 코일 양 끝의 극이 바뀐다','입자 자체가 모두 사라진다','자기장 방향은 절대 변하지 않는다'],'0','코일 자기장의 방향은 전류 방향과 관련됩니다. 전류 세기는 자기장의 세기와 관련됩니다.')};}
 });
 add('burning-conditions',{
  title:'물질의 성질이 달라지는 변화 비교',codes:['6과14-01'],initial:{kind:'paper',stage:'before'},fields:[field('kind','변화의 예',[['paper','종이 자르기'],['burn','종이 태운 결과'],['ice','얼음 녹이기']]),stages],
  view(s){const after=s.stage==='after',burn=s.kind==='burn',ice=s.kind==='ice';return{svg:rect(90,60,280,195,'#eef4f7')+(ice?(after?ellipse(230,220,90,15,'#90c6e3'):rect(190,130,80,80,'#b6dbed')):after&&burn?ellipse(230,220,75,15,'#626566'):after?rect(160,120,50,70,'#f0dbaf')+rect(250,150,50,70,'#f0dbaf'):rect(170,105,120,100,'#f0dbaf'))+label(after?'변화 뒤':'변화 전',230,285),text:!after?'처음 물질의 모양과 성질을 관찰합니다. 변화한 뒤에도 같은 물질인지 비교합니다.':burn?'종이를 태우면 재와 기체 등 성질이 다른 물질이 생깁니다. 단순히 모양만 작아진 변화와 구별합니다.':ice?'얼음이 녹아 물이 되어도 물이라는 물질 자체는 달라지지 않습니다. 상태가 달라진 변화입니다.':'종이를 잘라도 종이라는 물질의 성질은 그대로이고 크기와 모양이 달라집니다.',note:'종이를 태우는 직접 실행 지시가 아니라 교사가 준비한 전후 자료를 비교하는 모형입니다. 실제 연소 실험은 안전 장비와 교사 지도가 필요합니다.',check:check('새로운 물질이 생기는 변화의 예는?',['종이가 타서 재와 기체가 생김','종이를 가위로 자름','얼음이 녹음'],'0','모양이나 상태만 달라지는 변화와 물질의 성질 자체가 달라지는 변화를 구분합니다.')};}
 });

 add('cell-structure',{
  title:'동물·식물 세포의 공통점과 차이',codes:['9과02-01'],initial:{sample:'onion',zoom:'low',stain:'before',focus:'whole'},
  fields:[field('sample','준비된 표본',[['onion','양파 비늘줄기 표피'],['cheek','입안 상피']]),field('zoom','관찰 배율',[['low','낮음'],['high','높음']]),field('stain','염색',[['before','염색 전'],['after','염색 후']]),field('focus','모형 구조 표시',[['whole','표시 없음'],['nucleus','핵'],['membrane','세포막'],['wall','세포벽']])],
  view(s){const plant=s.sample==='onion',high=s.zoom==='high',stained=s.stain==='after';let svg='<defs><clipPath id="coreCellView"><circle cx="230" cy="145" r="120"/></clipPath></defs>'+circle(230,145,123,'#b8ced7')+'<g clip-path="url(#coreCellView)">'+circle(230,145,120,'#f8fbfc');
   const positions=high?[[230,145]]:[[165,100],[240,95],[310,115],[170,180],[250,175],[315,185]],scale=high?1.8:.72;
   for(const [x,y]of positions){svg+='<g transform="translate('+x+' '+y+') scale('+scale+')">';if(plant)svg+=rect(-45,-32,90,64,s.focus==='wall'?'#75a77b':'#b6cab3')+rect(-41,-28,82,56,s.focus==='membrane'?'#d58f45':'#d2ded6')+rect(-38,-25,76,50,'#f2f0d8');else svg+=ellipse(0,0,43,31,s.focus==='membrane'?'#d58f45':'#c1d5d9')+ellipse(0,0,39,27,'#edf5f7');svg+=ellipse(plant?-24:0,plant?8:0,8,11,stained||s.focus==='nucleus'?'#7c729e':'#dddbe4')+'</g>';}
   svg+='</g>'+label(high?'높은 배율: 좁은 범위':'낮은 배율: 넓은 범위',230,287);
   const focus=s.focus==='wall'?(plant?'세포벽이 바깥쪽에서 형태를 지지합니다.':'동물 세포에는 세포벽이 없습니다.'):s.focus==='membrane'?'세포막은 세포 안팎을 구분하고 물질 출입에 관여합니다.':s.focus==='nucleus'?'핵에는 유전 정보가 있으며 세포의 생명 활동에 관여합니다.':'전체 모양과 배열을 비교합니다.';
   return{svg,text:(plant?'양파 표피 세포는 비교적 규칙적인 경계가 이어져 보입니다.':'입안 상피 세포는 납작하고 불규칙한 외곽을 볼 수 있습니다.')+' '+focus+(stained?' 염색하면 핵 등 구조가 더 뚜렷해집니다.':' 염색 전에는 핵 등의 구별이 어려울 수 있습니다.'),note:'준비된 표본의 설명 그림이며 실제 현미경 사진이 아닙니다. 세포막은 세포벽과 맞닿아 광학현미경에서 따로 구별하기 어려우므로 모형에서 강조해 표시했습니다. 입안 세포 채취·염색은 교사 지도와 위생 관리가 필요합니다.',check:check('동물 세포에는 없고 식물 세포에는 있는 구조는?',['세포벽','핵','세포막'],'0','여기서 비교하는 동물·식물 세포 모두 핵과 세포막이 있지만 세포벽은 식물 세포에 있습니다.')};}
 });
 add('energy-conversion',{
  title:'자석과 코일의 상대 운동과 발전',codes:['10통과2-02-05'],initial:{moving:'magnet',direction:'in',pole:'N',speed:'slow'},
  fields:[field('moving','움직이는 물체',[['magnet','자석'],['coil','코일'],['none','둘 다 멈춤']]),field('direction','상대 거리 변화',[['in','가까워짐'],['out','멀어짐']]),field('pole','코일을 향한 극',[['N','N극'],['S','S극']]),field('speed','움직임',[['slow','느리게'],['fast','빠르게']])],
  view(s){const moving=s.moving!=='none',positive=(s.direction==='in')===(s.pole==='N'),deflect=moving?(positive?1:-1)*(s.speed==='fast'?40:20):0;let svg=rect(50,95,80,65,s.pole==='N'?'#cc7673':'#6d92c1')+label(s.pole,90,135,'#fff',24);for(let i=0;i<7;i++)svg+=ellipse(180+i*16,125,11,42,'none').replace('/>',' stroke="#b6874d" stroke-width="4"/>');svg+=circle(340,205,50,'#e7f1f5')+line(340,233,340+deflect,175,'#447e8a',4)+label('검류계',340,282)+label(moving?(s.direction==='in'?'서로 가까워짐':'서로 멀어짐'):'상대 운동 없음',230,40);return{svg,text:moving?'자석과 코일 중 어느 쪽을 움직여도 서로 가까워지거나 멀어지면 코일에 유도 전류가 흐릅니다. 상대 운동 방향 또는 자석의 극을 반대로 하면 검류계 바늘이 반대로 움직입니다. 같은 조건에서 더 빠르게 움직이면 더 크게 흔들립니다.':'자석이 코일 가까이에 있어도 둘 다 멈추어 코일을 지나는 자기장이 변하지 않으면 유도 전류가 흐르지 않습니다.',note:'같은 코일·자석·회로를 사용한 개념 모형입니다. 바늘의 좌우는 임의로 정한 검류계 단자 기준이며 수치는 전류 측정값이 아닙니다. 자석을 움직이는 운동 에너지가 전기 에너지로 전환되는 발전 원리를 비교합니다.',check:check('자석이 코일 가까이에 있다는 사실만으로 계속 전류가 흐르는가?',['아니다. 코일을 지나는 자기장의 변화가 필요하다','그렇다. 둘 다 멈춰도 계속 흐른다','코일을 움직이면 절대로 흐르지 않는다'],'0','자석과 코일의 상대 운동 등으로 코일을 지나는 자기장이 변할 때 유도 전류가 흐릅니다.')};}
 });
 add('mass-ratio',{
  title:'기체 반응의 부피 관계 자료 해석',codes:['9과16-05'],initial:{trial:'one',stage:'before'},fields:[field('trial','같은 온도·압력의 반응 자료',[['one','수소 2 · 산소 1'],['double','수소 4 · 산소 2'],['excess','수소 3 · 산소 1']]),stages],
  view(s){const after=s.stage==='after',scale=s.trial==='double'?2:1,excess=s.trial==='excess';const amounts=after?[excess?1:0,0,2*scale]:[excess?3:2*scale,scale,0];let svg='';['수소','산소','수증기'].forEach((name,i)=>{const x=70+i*150;svg+=rect(x,245-amounts[i]*40,65,amounts[i]*40,'#8cbccf')+label(name,x+32,280)+label(String(amounts[i]),x+32,230-amounts[i]*40);});return{svg,text:after?'같은 온도와 압력에서 반응에 참여한 수소 : 산소 : 생성된 수증기의 부피비는 2 : 1 : 2입니다.'+(excess?' 수소를 더 넣어도 산소가 부족하여 수소 1이 남습니다. 처음 넣은 전체 양과 실제 반응한 양을 구별합니다.':' 전체 양을 두 배로 해도 반응 부피비는 같습니다.'):'모두 같은 온도·압력에서 비교한 기체 부피 자료입니다. 숫자는 같은 단위의 상대적인 부피이며 물질별 부피를 비교합니다.',note:'물이 응결하지 않고 수증기로 존재하는 조건의 이상화된 반응 자료입니다. 수소·산소 혼합물을 직접 점화하는 활동 지시가 아닙니다. 반응 전후 총 기체 부피가 같아야 질량 보존인 것은 아닙니다.',check:check('같은 조건에서 완전히 반응한 수소·산소·생성 수증기의 부피비는?',['2 : 1 : 2','1 : 1 : 1','2 : 2 : 1'],'0','같은 온도·압력에서 반응에 참여한 기체와 생성된 기체 부피 사이에 간단한 정수비가 성립합니다.')};}
 });

 add('pea-genetics',{
  title:'세포분열과 염색체 관찰',codes:['9과21-01','9과21-02'],initial:{kind:'mitosis',step:'start'},
  fields:[field('kind','분열 종류',[['mitosis','체세포분열'],['meiosis','생식세포 형성']]),field('step','관찰 순서',[['start','염색체 복제 뒤'],['middle','염색체 나뉨'],['end','분열 결과']])],
  view(s){const mei=s.kind==='meiosis',end=s.step==='end',middle=s.step==='middle',cells=end?(mei?4:2):middle?2:1;let svg='';const centers=cells===4?[[130,90],[330,90],[130,220],[330,220]]:cells===2?[[125,150],[335,150]]:[[230,150]];for(const[x,y]of centers){svg+=ellipse(x,y,cells===1?145:85,cells===4?60:80,'#e1eff2');const n=(end||middle)&&mei?2:4;for(let i=0;i<n;i++){const xx=x-(n-1)*15+i*30,color=(middle&&mei?(x<230):end&&mei?(x<230):i%2===0)?'#b56f67':'#608abc',replicated=!end&&(!middle||mei);svg+=line(xx-6,y-15,xx+6,y+15,color,4);if(replicated)svg+=line(xx+6,y-15,xx-6,y+15,color,4);}}return{svg:svg+label(end?(mei?'염색체 수가 절반인 세포 4개':'염색체 수가 같은 세포 2개'):middle?(mei?'상동 염색체가 먼저 나뉨':'복제된 염색 분체가 나뉨'):'복제되어 두 가닥인 염색체',230,298),text:end?(mei?'생식세포 형성 과정에서는 두 번의 분열을 거쳐 염색체 수가 절반인 세포가 만들어집니다. 수정으로 두 생식세포가 합쳐지면 염색체 수가 회복됩니다.':'체세포분열로 만들어진 두 세포는 원래 세포와 염색체 수가 같습니다. 세포의 수가 늘어 개체가 자라거나 손상된 부분을 회복합니다.'):middle?(mei?'첫 분열에서 상동 염색체가 서로 나뉩니다. 그 뒤 복제된 염색 분체가 나뉘어 최종 세포가 만들어집니다.':'복제된 염색 분체가 양쪽으로 나뉘어 같은 염색체 구성이 전달됩니다.'):'염색체는 분열 전에 복제됩니다. 모형은 염색체 4개인 세포를 가정하고 염색체 행동을 비교합니다.',note:'실제 양파 뿌리 표본 사진이 아니라 염색체 행동을 단순화한 모형입니다. 염색체의 색은 출처 구별용입니다. 감수분열의 교차·분자 기작·단계 이름 암기는 이 확인 문제에 넣지 않습니다.',check:check('체세포분열과 생식세포 형성의 결과를 바르게 비교하면?',['체세포분열은 염색체 수 유지, 생식세포 형성은 절반','둘 다 항상 염색체 수 두 배','둘 다 염색체가 사라짐'],'0','체세포분열은 같은 염색체 수를 유지하고, 생식세포 형성에서는 염색체 수가 절반이 됩니다.')};}
 });
 add('cell-membrane',{
  title:'효소 유무·가열에 따른 작용 비교',codes:['10통과1-03-05'],initial:{sample:'fresh',stage:'before'},
  fields:[field('sample','과산화 수소에 넣을 시료',[['water','같은 양의 물'],['fresh','생감자'],['heated','충분히 가열한 감자']]),stages],
  view(s){const after=s.stage==='after',active=after&&s.sample==='fresh';let svg=jar(175,130,'#c4e0ec');if(s.sample!=='water')svg+=ellipse(230,205,30,15,'#dcc699');if(active)for(let i=0;i<12;i++)svg+=circle(195+(i%4)*23,115+Math.floor(i/4)*28,5,'#fff');return{svg:svg+label(active?'산소 기포가 많이 나타남':after?'기포가 적거나 거의 없음':'처음 모습',230,280),text:!after?'과산화 수소의 양·농도·온도와 시료의 양을 같게 하여 비교합니다. 가열한 감자는 식혀서 처음 온도를 맞춘 조건입니다.':active?'생감자 속 효소가 과산화 수소의 분해를 촉진하여 산소 기포가 많이 나타납니다. 효소는 생명 시스템의 화학 반응을 촉진합니다.':s.sample==='heated'?'충분히 가열하면 효소의 구조가 변하여 작용이 약해질 수 있습니다. 식혀 같은 온도에서 비교해도 생감자보다 기포가 적거나 거의 없습니다.':'같은 양의 물을 넣은 대조군과 비교하여 감자 속 효소가 반응을 촉진하는지 알아봅니다.',note:'교사가 준비한 시료의 상대적 반응 모형입니다. 실제 기포 수·반응 시간은 조건에 따라 달라집니다. 과산화 수소를 피부에 바르거나 마시지 않으며 실험은 보안경과 교사 지도 아래 진행합니다. 효소 반응 속도식·Km 계산은 다루지 않습니다.',check:check('생감자와 가열한 감자를 비교할 때 먼저 같게 맞출 것은?',['반응 시작 온도와 시료·용액의 양','효소가 모두 똑같이 작용한다는 결론','용액의 양은 서로 다르게 한다'],'0','다른 조건을 통제해야 가열이 효소 작용에 미치는 영향을 비교할 수 있습니다.')};}
 });
 add('flame-ions',{
  title:'같은 족 원소의 성질 비교',codes:['9과11-03'],initial:{group:'alkali',stage:'before'},fields:[field('group','준비된 관찰 자료',[['alkali','1족: 나트륨·칼륨'],['noble','18족: 헬륨·네온']]),stages],
  view(s){const alkali=s.group==='alkali',after=s.stage==='after';let svg=jar(65,130,'#c0ddeb')+jar(285,130,'#c0ddeb')+label(alkali?'나트륨':'헬륨',120,35)+label(alkali?'칼륨':'네온',340,35);if(alkali){svg+=rect(105,105,25,12,'#b5bbc0')+rect(325,105,25,12,'#b5bbc0');if(after)for(let i=0;i<8;i++){svg+=circle(94+(i%3)*22,120+Math.floor(i/3)*20,4,'#fff')+circle(310+(i%3)*22,120+Math.floor(i/3)*20,5,'#fff');}}return{svg,text:alkali?(after?'준비된 시범 관찰 자료에서 나트륨과 칼륨은 모두 물과 반응합니다. 반응 정도는 같지 않아도 같은 족 원소에서 비슷한 성질을 찾을 수 있습니다.':'같은 족에 속한 나트륨과 칼륨의 물과의 반응 자료를 비교합니다.'):'헬륨과 네온은 18족 원소이며 일상적인 조건에서 다른 물질과 잘 반응하지 않는 비슷한 성질이 있습니다. 모든 원소가 물과 반응하는 것은 아닙니다.',note:'교사의 시범 자료를 설명하는 그림입니다. 알칼리 금속을 물에 넣는 직접 실험 지시가 아니며 절대 따라 하지 않습니다. 반응식·원자 전자 배치로 반응성 차이를 설명하거나 주기성을 계산하지 않습니다.',check:check('같은 족 원소를 관찰하여 추론할 수 있는 것은?',['비슷한 화학적 성질을 보이는 원소들이 있다','모든 원소의 반응 정도가 완전히 같다','같은 족 원소는 모두 같은 원소다'],'0','같은 족에서 비슷한 성질이 나타날 수 있지만 서로 다른 원소이며 반응 정도까지 같지는 않습니다.')};}
 });
 add('neutralization-common',{
  title:'산·염기를 섞을 때 온도 비교',codes:['10통과2-01-04','10통과2-01-05'],initial:{acid:'50',stage:'before'},fields:[field('acid','전체 100 mL에서 산의 부피',[['20','산 20 + 염기 80'],['40','산 40 + 염기 60'],['50','산 50 + 염기 50'],['60','산 60 + 염기 40'],['80','산 80 + 염기 20']]),stages],
  view(s){const acid=+s.acid,base=100-acid,after=s.stage==='after',temp=a=>20+Math.min(a,100-a)*.01*13.7,t=after?temp(acid):20;let svg=jar(25,105,'#b1d9e7')+label(t.toFixed(1)+' ℃',80,270)+line(190,240,430,240)+line(190,240,190,55);const values=[20,40,50,60,80],point=a=>[190+(a-20)*3.8,230-(temp(a)-20)*22];for(let i=0;i<values.length;i++){const p=point(values[i]);if(i)svg+=line(...point(values[i-1]),...p,'#5394a2',3);svg+=circle(p[0],after&&values[i]===acid?p[1]:p[1],after&&values[i]===acid?7:3,after&&values[i]===acid?'#d18b37':'#5394a2');}for(const a of values)svg+=label(String(a),point(a)[0],258,'#173f50',11);for(const value of [20,24,28])svg+=label(String(value),176,234-(value-20)*22,'#173f50',11);svg+=label('산 부피 (mL) →',315,289)+label('혼합 뒤 온도 (℃)',310,35);return{svg,text:after?'산 '+acid+' mL와 염기 '+base+' mL를 섞은 가상 결과는 '+t.toFixed(1)+' ℃입니다. 중화 반응에서 열을 방출하여 온도가 올라갑니다. 같은 농도·같은 전체 부피에서는 반응하는 양이 가장 많은 50 + 50 조건의 온도 상승이 가장 큽니다.':'두 용액의 처음 온도는 모두 20.0 ℃입니다. 산과 염기를 섞은 뒤의 온도를 비교합니다. 오른쪽 그래프는 다섯 조건의 혼합 뒤 결과를 비교한 모형 자료입니다.',note:'같은 농도의 묽은 염산·수산화 나트륨, 같은 처음 온도·전체 부피, 열 손실과 희석열을 무시한 가상 자료입니다. 서로 다른 농도의 용액을 같은 부피로 섞는다고 언제나 중화되는 것은 아닙니다. 실제 실험은 보안경·장갑과 교사 지도가 필요합니다. pH 적정곡선·엔탈피 계산은 다루지 않습니다.',check:check('같은 농도·같은 처음 온도에서 전체 부피를 일정하게 비교하는 까닭은?',['섞는 비율에 따른 온도 변화를 공정하게 비교하려고','모든 농도에서 같은 부피면 항상 중화되므로','중화 반응에서 열이 전혀 나지 않으므로'],'0','농도·처음 온도·전체 부피 등을 통제하고 섞는 비율에 따른 온도 변화를 비교합니다.')};}
 });

 add('density-buoyancy',{
  title:'순수한 물질의 녹는점·끓는점 비교',codes:['9과08-01'],initial:{kind:'melt',sample:'A',amount:'one',step:'before'},
  fields:[field('kind','가열 관찰',[['melt','녹는점 비교'],['boil','끓는점 비교']]),field('sample','가상 순수 물질',[['A','물질 A'],['B','물질 B']]),field('amount','같은 물질의 양',[['one','기준 양'],['two','두 배의 양']]),field('step','관찰 구간',[['before','상태 변화 전'],['during','상태 변화 중'],['after','상태 변화 후']])],
  view(s){const melt=s.kind==='melt',point=melt?(s.sample==='A'?20:40):(s.sample==='A'?80:100),stage={before:0,during:1,after:2}[s.step],temperature=point+[-20,0,20][stage];let svg=line(60,255,410,255)+line(60,255,60,35);const points=[[70,230],[170,155],[290,155],[395,60]];for(let i=0;i<3;i++)svg+=line(...points[i],...points[i+1],i===stage?'#d18b37':'#83abb5',5);svg+=label(point+' ℃',110,140)+label('가열 순서 →',280,290)+label('현재 '+temperature+' ℃',295,35);return{svg,text:s.step==='during'?'상태가 변하는 동안 온도가 '+point+' ℃로 일정한 구간이 나타납니다. 이 값은 모형 물질 '+s.sample+'의 '+(melt?'녹는점':'끓는점')+'입니다. 같은 압력에서 같은 순수 물질은 양이 달라도 이 온도가 같습니다.':s.step==='before'?'같은 압력에서 가상 순수 물질을 가열합니다. 물질 종류와 양을 바꿔 온도가 일정한 구간을 비교합니다.':'상태 변화가 끝나고 계속 가열하면 온도가 다시 올라갑니다. 물질 A와 B는 서로 다른 녹는점·끓는점을 가진 모형으로, 이런 특성을 물질 구별에 이용할 수 있습니다.',note:'A·B는 관찰 자료 해석용 가상 물질이며 실제 시약이나 측정 자료가 아닙니다. 온도는 설명용 설정값입니다. 양이 달라지면 필요한 열량·시간은 달라질 수 있어 가열 순서 축은 같은 실제 시간을 뜻하지 않습니다. 혼합물·압력 변화에는 그대로 적용하지 않습니다.',check:check('같은 압력에서 순수한 물질의 양만 늘리면 녹는점은?',['같다','항상 두 배가 된다','항상 0 ℃가 된다'],'0','녹는점·끓는점은 같은 조건에서 물질을 구별하는 특성입니다. 양에 따른 가열 시간과 구별합니다.')};}
 });
 return result;
}
if(typeof window!=='undefined')window.scienceCoreExtensions=scienceCoreFactory;
if(typeof module!=='undefined')module.exports=scienceCoreFactory;
