/* Curriculum observations, not photographs, patient data, or real measurements. */
window.scienceSupplementExtensions=({line,label,rect,jar,field})=>({
 immune:{
  title:'항A·항B 시약으로 미지 혈액형 판정',codes:['12생과02-06'],initial:{sample:'가',stage:'before',answer:'unknown'},
  fields:[field('sample','가상 표본',[['가','표본 가'],['나','표본 나'],['다','표본 다'],['라','표본 라']]),field('stage','반응 관찰',[['before','시약 넣기 전'],['after','두 시약의 반응 확인']]),field('answer','나의 판정',[['unknown','아직 판정하지 않음'],['A','A형'],['B','B형'],['AB','AB형'],['O','O형']])],
  view(s){const type={가:'A',나:'O',다:'AB',라:'B'}[s.sample],after=s.stage==='after';let svg='';for(const [index,antigen]of ['A','B'].entries()){const x=125+index*210,clump=after&&type.includes(antigen);svg+='<circle cx="'+x+'" cy="150" r="83" fill="#fff0f0" stroke="#d4a3a3"/>'+label('항'+antigen+' 시약',x,40);for(let n=0;n<18;n++){const a=n*Math.PI*2/18,cx=clump?x+(n%3-1)*28+(Math.floor(n/3)%2)*7:x+Math.cos(a)*58,cy=clump?145+(Math.floor(n/3)-2)*10:150+Math.sin(a)*58;svg+='<circle cx="'+cx+'" cy="'+cy+'" r="7" fill="#bf454e"/>';}svg+=label(after?(clump?'응집 있음':'응집 없음'):'반응 전',x,265);}
   return{svg,text:!after?'응집 여부는 시약 반응 뒤 판정합니다. 각 표본에 항A·항B 시약을 각각 반응시켜 비교하세요.':s.answer==='unknown'?'항A에만 응집하면 A형, 항B에만 응집하면 B형, 모두 응집하면 AB형, 모두 응집하지 않으면 O형입니다. 관찰 결과로 판정해 보세요.':s.answer===type?'판정이 맞았습니다. 표본 '+s.sample+'는 '+type+'형입니다. 해당 항원과 항체 사이의 특이적 반응을 근거로 설명하세요.':'판정을 다시 확인하세요. 한 시약만 보지 말고 항A·항B의 응집 여부를 함께 비교합니다.',note:'적혈구와 응집을 단순화한 가상 표본입니다. 실제 혈액 취급 활동이나 수혈 지침이 아니며, 실제 수혈 적합성은 이 판정만으로 결정할 수 없습니다.'};}
 },
 'stars-universe':{
  title:'연주 시차와 우리은하 관찰',codes:['9과15-01','9과15-02'],initial:{kind:'parallax',distance:'near',position:'left',object:'galaxy'},
  fields:s=>[field('kind','관찰 주제',[['parallax','연주 시차'],['galaxy','우리은하·성운·성단']]),...(s.kind==='parallax'?[field('distance','별까지 거리',[['near','가까운 별'],['far','더 먼 별']]),field('position','지구의 관측 위치',[['left','처음 위치'],['right','6개월 뒤 반대쪽']])]:[field('object','관찰 대상',[['galaxy','우리은하'],['nebula','성운'],['cluster','성단']])])],
  view(s){if(s.kind==='parallax'){const shift=s.distance==='near'?65:25,x=s.position==='left'?230-shift:230+shift;return{svg:rect(15,25,430,115,'#213751')+[50,115,230,340,410].map((x,i)=>label('·',x,65+(i%2)*30,'#fff',36)).join('')+label('★',x,109,'#ffd977',30)+label('먼 배경 별에 대한 겉보기 위치',230,165)+line(155,250,305,250)+label('지구  ●',s.position==='left'?155:305,230,'#287daa')+label('☀',230,235,'#c78a19',28),text:'지구가 공전하여 관측 위치가 달라지면 가까운 별은 먼 배경 별에 대해 위치가 달라 보입니다. 같은 관측 간격에서 가까운 별일수록 이 변화가 큽니다. 연주 시차는 6개월 간격 최대 각도 차이의 절반입니다.',note:'위 화면은 관측 방향의 비교 모형으로 실제 각도·거리 비율이 아닙니다. 별 자체가 좌우로 이동한 것으로 해석하지 않습니다. 이 학년에서는 거리 공식을 도입하지 않습니다.'};}
   let svg='';if(s.object==='galaxy'){svg='<ellipse cx="230" cy="150" rx="195" ry="100" fill="#d6dfef"/><ellipse cx="230" cy="150" rx="60" ry="40" fill="#9dadd0"/>'+label('중심부',230,155)+label('● 태양계',337,180,'#a46b06')+label('위에서 본 원반 모형',230,285);}else if(s.object==='nebula'){svg='<path d="M80 155 Q65 30 205 75 Q335 20 378 145 Q430 245 270 220 Q110 285 80 155" fill="#bccde6" opacity=".8"/>'+label('기체와 티끌',230,155);}else{svg=Array.from({length:35},(_,i)=>label('·',230+Math.cos(i*2.4)*Math.sqrt(i)*18,150+Math.sin(i*2.4)*Math.sqrt(i)*14,'#536faa',28)).join('');}return{svg,text:s.object==='galaxy'?'우리은하는 중심부가 두드러진 원반 모양의 막대 나선 은하이며, 태양계는 중심에서 떨어진 원반에 있습니다. 원반의 지름은 대략 10만 광년 규모입니다.':s.object==='nebula'?'성운은 우주 공간에 있는 기체와 티끌이 모여 있는 것입니다. 별이 모인 성단과 구별합니다.':'성단은 별들이 무리를 이루고 있는 것입니다. 성운의 기체·티끌과 구별합니다.',note:'관찰 특징을 비교하는 개략도이며 천체 사진이 아닙니다. 우리은하의 나선팔·막대·헤일로를 모두 표현하지 않았고 정확한 축척도 아닙니다.'};}
 },
 microscope:{
  title:'식물 세포의 구조와 기관의 연결',codes:['6과11-01','6과11-02'],initial:{kind:'cell',part:'wall',stage:'before'},
  fields:s=>[field('kind','관찰 주제',[['cell','식물 세포'],['stem','줄기의 물 이동'],['leaf','잎에서 나가는 물'],['starch','잎에서 만들어진 양분']]),...(s.kind==='cell'?[field('part','구조 이름',[['wall','세포벽'],['membrane','세포막'],['nucleus','핵']])]:[field('stage','관찰 시점',[['before','처음'],['after','시간이 지난 뒤']])])],
  view(s){if(s.kind==='cell')return{svg:'<rect x="100" y="40" width="260" height="220" rx="8" fill="#eef3d7" stroke="'+(s.part==='wall'?'#c87124':'#769c60')+'" stroke-width="12"/><rect x="115" y="55" width="230" height="190" rx="8" fill="none" stroke="'+(s.part==='membrane'?'#c87124':'#86afa6')+'" stroke-width="4"/><ellipse cx="300" cy="175" rx="22" ry="27" fill="'+(s.part==='nucleus'?'#c87124':'#a99ac9')+'"/>'+label({wall:'세포벽',membrane:'세포막',nucleus:'핵'}[s.part],230,290),text:'식물은 세포로 이루어져 있습니다. 세포벽, 세포막, 핵의 위치와 이름을 구별합니다. 세포막은 세포벽 안쪽에 있습니다.',note:'구조를 구별하기 위해 두께와 색을 과장한 모형입니다. 실제 양파 표피의 세포막은 세포벽에 붙어 뚜렷하게 구별되지 않을 수 있습니다. 동물 세포 비교나 삼투 원리는 이 학년의 시험 항목으로 넣지 않습니다.'};
   const after=s.stage==='after';if(s.kind==='starch')return{svg:'<ellipse cx="140" cy="150" rx="70" ry="100" fill="'+(after?'#293e68':'#82ac69')+'"/><ellipse cx="330" cy="150" rx="70" ry="100" fill="'+(after?'#b9a47b':'#82ac69')+'"/>'+label('빛을 받은 잎',140,35)+label('빛을 가린 잎',330,35),text:after?'준비된 잎에 아이오딘 용액을 떨어뜨리면 빛을 받은 잎에서 청람색 반응이 나타납니다. 잎에서 녹말이 만들어졌음을 알아봅니다.':'남아 있던 녹말을 없앤 식물에서 빛을 받은 잎과 가린 잎을 비교합니다. 물 등 빛 이외의 조건은 같게 합니다.',note:'교사가 안전하게 전처리한 잎의 반응을 비교하는 모형이며, 실제 관찰이나 실험 절차 전체를 대신하지 않습니다. 알코올을 직접 가열하지 않습니다. 잎에서 만들어진 양분은 다른 기관으로 옮겨져 쓰이거나 저장됩니다.'};if(s.kind==='stem')return{svg:jar(175,70,'#e5a1a4')+line(230,220,230,45,after?'#c7505d':'#72a663',14)+'<ellipse cx="177" cy="90" rx="53" ry="18" fill="#87b46c" transform="rotate(25 177 90)"/><ellipse cx="281" cy="70" rx="53" ry="18" fill="#87b46c" transform="rotate(-25 281 70)"/>'+label(after?'줄기의 일부가 물들음':'색소 물에 줄기 꽂기',230,285),text:after?'색소 물에 꽂아 둔 줄기의 일부가 물들어 있습니다. 줄기가 물의 이동 통로임을 추리할 수 있습니다. 뿌리에서 흡수한 물은 줄기를 지나 잎으로 이동합니다.':'절단한 줄기를 색소 물에 꽂은 처음 모습과 시간이 지난 뒤의 모습을 비교합니다.',note:'색소 물의 이동을 단순화한 관찰 모형입니다. 뿌리에서 직접 흡수하는 장면을 관찰한 것과는 구별합니다. 잎에서 만들어진 양분도 다른 기관으로 이동하여 이용됩니다.'};
   let svg=line(230,265,230,95,'#729d5e',12)+'<ellipse cx="190" cy="140" rx="55" ry="22" fill="#83ae68"/><ellipse cx="273" cy="115" rx="55" ry="22" fill="#83ae68"/><rect x="110" y="55" width="240" height="175" rx="25" fill="#b9d6e2" fill-opacity=".25" stroke="#86aabd"/>';if(after)svg+=[130,175,220,280,325].map((x,i)=>'<circle cx="'+x+'" cy="'+(80+i%2*20)+'" r="5" fill="#71aed0"/>').join('');return{svg,text:after?'잎에서 수증기로 나간 물이 봉지 안쪽에 물방울로 맺힐 수 있습니다. 잎이 있는 가지와 없는 가지를 같은 조건에서 비교하면 잎의 역할을 추리하는 데 도움이 됩니다.':'마른 투명 봉지로 잎이 있는 가지를 감싼 처음 모습과 시간이 지난 뒤를 비교합니다.',note:'봉지 안 물방울이 모두 잎 때문이라고 단정하지 않도록 처음 봉지의 물기와 토양 증발 등 다른 조건을 통제합니다. 실제 관찰값이 아닌 비교 모형입니다.'};}
 },
 'weather-watch':{
  title:'이슬·안개·구름과 기압에 따른 바람',codes:['6과06-02','6과06-03'],initial:{kind:'dew',direction:'right'},
  fields:s=>[field('kind','관찰 주제',[['dew','이슬'],['fog','안개'],['cloud','구름'],['wind','기압과 바람']]),...(s.kind==='wind'?[field('direction','고기압이 있는 쪽',[['right','왼쪽에 고기압'],['left','오른쪽에 고기압']])]:[])],
  view(s){if(s.kind==='wind'){const right=s.direction==='right';return{svg:label(right?'고기압':'저기압',90,135)+label(right?'저기압':'고기압',370,135)+label(right?'→':'←',230,145,'#34749b',65)+label('바람이 부는 방향',230,215),text:'이 학년에서는 공기가 고기압에서 저기압 쪽으로 이동하여 바람이 분다는 관계를 알아봅니다. 일반적으로 고기압 부근은 맑고, 저기압 부근은 구름과 비가 나타나기 쉽습니다.',note:'실제 바람에는 지구 자전·지형 등도 영향을 줍니다. 여기서는 학년 범위에 맞추어 기압 차이에 따른 방향만 비교합니다. 언제나 맑거나 비가 온다는 뜻은 아닙니다.'};}
   const y=s.kind==='cloud'?70:205;return{svg:rect(0,255,460,45,'#c5d6b0')+(s.kind==='dew'?'<ellipse cx="230" cy="235" rx="100" ry="20" fill="#8dad74"/>':'')+Array.from({length:18},(_,i)=>'<circle cx="'+(90+i%6*55)+'" cy="'+(y+Math.floor(i/6)*14)+'" r="'+(s.kind==='dew'?4:7)+'" fill="#93bbd4"/>').join('')+label({dew:'물체 표면에 맺힘',fog:'지표 가까운 공기 중',cloud:'높은 공기 중'}[s.kind],230,35),text:'수증기가 작은 물방울로 변한 모습을 비교합니다. 이슬은 물체 표면에 맺히며, 안개는 지표 가까운 공기 중에, 구름은 높은 공기 중에 떠 있습니다. 구름에는 작은 얼음 알갱이가 포함되기도 합니다.',note:'물방울은 보기 쉽게 크게 그렸습니다. 비·눈이 만들어지는 상세 과정이나 단열 팽창은 이 학년의 시험 내용으로 다루지 않습니다.'};}
 },
 'land-sea':{
  title:'바닷물 높이의 변화와 갯벌',codes:['4과06-03'],initial:{water:'high'},
  fields:[field('water','같은 바닷가 관찰',[['high','바닷물이 높을 때'],['low','바닷물이 낮을 때']])],
  view(s){const high=s.water==='high';return{svg:rect(0,180,460,90,'#b9a081')+'<path d="M0 '+(high?'120':'210')+' H460 V270 H0 Z" fill="#86bad6" opacity=".8"/>'+line(60,80,60,270)+line(47,120,75,120)+line(47,210,75,210)+label('같은 기준 기둥',90,40)+(high?'':label('드러난 갯벌',265,180)),text:high?'밀물 때 바닷물이 들어와 높아지면 갯벌이 물에 잠깁니다. 같은 장소의 기준 기둥과 비교합니다.':'썰물 때 바닷물이 빠져나가 낮아지면 갯벌이 드러납니다. 갯벌은 여러 생물의 서식지이며 바닷가 생태계를 지키는 데 중요합니다.',note:'높이 변화를 비교하는 모형입니다. 발생 원인은 이 학년에서 다루지 않습니다. 갯벌을 보전하려면 쓰레기를 버리지 않고 생물의 서식지를 훼손하지 않아야 합니다. 실제 방문은 안전한 출입 시간과 현장 안내를 따릅니다.'};}
 },
 'sound-vibration':{
  title:'소리의 전달과 소음 줄이기',codes:['4과07-03'],initial:{kind:'string',condition:'on'},
  fields:s=>[field('kind','관찰 상황',[['string','실 전화기'],['noise','같은 소리의 소음 줄이기']]),field('condition','비교 조건',s.kind==='string'?[['on','실을 팽팽하게'],['off','실을 느슨하게']]:[['on','창문을 닫음'],['off','창문을 열음']])],
  view(s){const on=s.condition==='on';let svg;if(s.kind==='string')svg=rect(40,110,50,70,'#cbbda9')+rect(370,110,50,70,'#cbbda9')+(on?line(90,145,370,145,'#957f65',2):'<path d="M90 145 Q230 280 370 145" fill="none" stroke="#957f65" stroke-width="2"/>')+label('말하기',65,70)+label('듣기',395,70);else svg=label('소리',85,145)+rect(205,65,25,185,on?'#a9c4d4':'#e8eef2')+label(on?'닫힌 창문':'열린 창문',230,285)+label('듣는 곳',365,145);return{svg,text:s.kind==='string'?(on?'실이 팽팽할 때 실을 통해 소리가 더 잘 전달되는 것을 관찰할 수 있습니다. 공기뿐 아니라 물체를 통해서도 소리가 전달됩니다.':'실을 느슨하게 하면 소리가 잘 전달되지 않을 수 있습니다. 말하는 크기와 컵·실의 종류를 같게 하고 비교합니다.'):(on?'창문을 닫으면 바깥 소음이 줄어들 수 있습니다. 소리의 크기 줄이기, 문 닫기, 소음원에서 멀어지기 등 상황에 맞는 방법을 고릅니다.':'같은 소리와 같은 듣는 위치에서 창문의 상태만 바꾸어 비교합니다.'),note:'들리는 정도를 비교하는 관찰 안내 모형이며 실제 소리를 재생하거나 측정하지 않습니다. 소리 전달의 입자 수준 원리나 수치 계산은 다루지 않습니다.'};}
 },
 'rock-layers':{
  title:'화석의 특징으로 과거 환경 추리하기',codes:['6과01-03'],initial:{fossil:'shell'},
  fields:[field('fossil','특징이 드러난 화석 모형',[['shell','바다 조개 화석'],['leaf','나뭇잎 화석']])],
  view(s){const shell=s.fossil==='shell';return{svg:rect(40,30,380,245,'#d4c3a5')+(shell?'<path d="M230 220 Q55 140 150 75 Q230 20 310 75 Q405 140 230 220" fill="#ac9373" stroke="#816b51"/>'+[150,190,230,270,310].map(x=>line(230,220,x,80,'#816b51',3)).join(''):'<path d="M230 240 Q60 120 230 55 Q400 120 230 240" fill="#ac9373"/>'+line(230,230,230,65,'#816b51',4)+[110,145,180].map(y=>line(230,y,175,y-30,'#816b51',2)+line(230,y,285,y-30,'#816b51',2)).join('')),text:shell?'껍데기 모양이 남은 바다 조개 화석은 이 지층이 만들어질 당시 바다 환경이었을 가능성을 뒷받침합니다. 화석이 옮겨져 쌓였을 가능성 등도 함께 살핍니다.':'잎의 모양과 잎맥이 남아 있습니다. 과거에 식물이 살았다는 증거이며, 어떤 식물인지와 다른 화석·지층 자료를 함께 보면 환경을 더 구체적으로 추리할 수 있습니다.',note:'특징을 비교하기 위한 그림이며 실제 표본 사진이 아닙니다. 화석 하나만으로 정확한 기온·연대나 당시 모든 환경을 확정하지 않습니다.'};}
 },
 'minerals-rocks':{
  title:'암석의 생성 과정과 순환',codes:['9과09-03'],initial:{process:'cool'},
  fields:[field('process','어떤 과정이 일어났나요?',[['cool','마그마가 식음'],['deposit','퇴적물이 쌓여 굳음'],['change','높은 열과 압력을 받음'],['melt','암석이 녹음']])],
  view(s){const names={cool:'화성암',deposit:'퇴적암',change:'변성암',melt:'마그마'},color={cool:'#968e89',deposit:'#b5a083',change:'#a299a8',melt:'#e6a078'};let svg=rect(125,60,210,175,color[s.process])+label(names[s.process],230,155,'#21313d',24);if(s.process==='deposit')svg+=[85,120,180,215].map(y=>line(130,y,330,y,'#8e7d66',3)).join('');return{svg,text:{cool:'마그마가 식어 굳으면 화성암이 됩니다. 현무암·유문암·화강암·반려암을 생성 조건과 관련지어 비교합니다.',deposit:'퇴적물이 쌓이고 굳어 퇴적암이 됩니다. 이암·사암·역암·석회암을 관찰합니다. 지표의 암석이 부서지고 이동하여 퇴적물이 될 수 있습니다.',change:'암석이 녹지 않은 상태에서 높은 열과 압력으로 성질이 바뀌면 변성암이 됩니다. 편암·편마암·대리암·규암이 있습니다.',melt:'암석이 녹으면 마그마가 될 수 있습니다. 식음·퇴적·변성·녹음 등의 과정을 거치며 암석이 순환합니다. 반드시 정해진 한 순서만 따르는 것은 아닙니다.'}[s.process],note:'생성 과정을 구별하는 개념 모형입니다. 색·무늬만으로 모든 암석을 판정할 수 없고, 암석마다 가능한 변화 조건과 경로가 다릅니다.'};}
 }
});
