const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),map=require(path.join(root,'curriculum-map.js'));
async function serve(){const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));return{server,url:'http://127.0.0.1:'+server.address().port};}
async function route(page){await page.route('**/*',r=>{const host=new URL(r.request().url()).hostname;return host==='127.0.0.1'?r.continue():r.abort();});}
test('WebKit touch: all 104 apps load and original questions respond',{timeout:240000},async()=>{
 const {webkit}=require('playwright'),{server,url}=await serve();let browser;const errors=[],small=[];
 try{browser=await webkit.launch({headless:true});const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,isMobile:true,deviceScaleFactor:2});const page=await context.newPage();await route(page);let current='';page.on('pageerror',e=>errors.push(current+': '+e.message));
  for(const slug of Object.keys(map)){current=slug;await page.goto(url+'/'+slug+'/');await page.waitForSelector('.quiz-card',{state:'attached'});const section=page.locator('details.quiz-section');if(await section.count())await section.locator('summary').tap();const card=page.locator('.quiz-card').first(),answer=await card.getAttribute('data-answer');await card.locator('input[value="'+answer+'"]').locator('..').tap();await card.locator('.answer-button').tap();assert(/정답|맞았/.test(await card.locator('.answer-result').textContent()),slug);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,slug+' overflow');
   const undersized=await page.locator('.control-panel button,.answer-button,.required-check button,.supplement-check button,.quiz-heading').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length&&!n.closest('[hidden]')&&n.getBoundingClientRect().height<43).map(n=>({text:n.textContent.trim().slice(0,24),height:Math.round(n.getBoundingClientRect().height)})));if(undersized.length)small.push({slug,items:undersized});if(Object.keys(map).indexOf(slug)%20===0)console.log('WebKit checked: '+slug);
  }
  assert.deepEqual(errors,[]);assert.deepEqual(small,[],'touch targets below 44px');console.log('WebKit touch: 104 app loads and 104 original answer interactions passed');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
test('Chromebook keyboard and WebKit tablet touch: filtering, answers, rotation and focus',{timeout:120000},async()=>{
 const {chromium,webkit}=require('playwright'),{server,url}=await serve();
 try{for(const profile of ['chromebook','tablet-webkit']){const tablet=profile==='tablet-webkit',browser=await (tablet?webkit:chromium).launch({headless:true,...(!tablet?{executablePath:process.env.SCIENCE_BROWSER}:{})});try{const context=await browser.newContext({viewport:tablet?{width:820,height:1180}:{width:1366,height:768},hasTouch:tablet,isMobile:tablet,deviceScaleFactor:tablet?2:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await route(page);await page.goto(url+'/exam-review.html');await page.waitForSelector('.exam-answers');await page.evaluate(()=>document.fonts.ready);
   if(tablet){await page.evaluate(()=>{window.schoolTouches=0;document.addEventListener('touchstart',()=>window.schoolTouches++,{passive:true});});await page.locator('[data-exam-grade="중1"]').tap();assert(await page.evaluate(()=>window.schoolTouches>0),'real synthetic touch events');}else{await page.keyboard.press('Tab');assert.equal(await page.locator('.exam-back').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Tab');assert.equal(await page.locator('[data-exam-grade="초3"]').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');}
   const first=await page.locator('.exam-question').getAttribute('data-exam-id'),answer=page.locator('[data-exam-answer="1"]');if(tablet)await answer.tap();else{await answer.focus();await page.keyboard.press('Space');}assert.equal(await answer.getAttribute('aria-pressed'),'true');
   for(const size of tablet?[[1180,820],[768,1024],[1024,768],[744,1133]]:[[1093,614],[1280,720]]){await page.setViewportSize({width:size[0],height:size[1]});assert.equal(await page.locator('.exam-question').getAttribute('data-exam-id'),first);assert.equal(await answer.getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,profile+' '+size);}
   const next=page.locator('[data-exam-next]');if(tablet)await next.tap();else{await next.focus();await page.keyboard.press('Enter');}assert.notEqual(await page.locator('.exam-question').getAttribute('data-exam-id'),first);assert.equal(await page.locator('.exam-question h2').evaluate(n=>n===document.activeElement),true);if(tablet)await page.locator('[data-exam-prev]').tap();else{await page.locator('[data-exam-prev]').focus();await page.keyboard.press('Enter');}assert.equal(await answer.getAttribute('aria-pressed'),'true');
   await page.locator('.exam-reset')[tablet?'tap':'click']();assert.equal(await page.locator('.exam-feedback').textContent(),'');assert.deepEqual(errors,[]);
   const visible=await page.locator('.exam-widget button,.exam-widget select').evaluateAll(ns=>ns.filter(n=>n.getClientRects().length).every(n=>n.getBoundingClientRect().height>=44));assert(visible,profile+' touch target');console.log(profile+': input, answer state, resized viewport, reset and focus passed');
  }finally{await browser.close();}}
 }finally{await new Promise(r=>server.close(r));}
});
