const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),out=path.resolve(__dirname,'../docs/science-lab-audit-2026-09-20/visual-recheck/verified');fs.mkdirSync(out,{recursive:true});
for(const engine of ['chromium','webkit'])test(engine+': fractions stay mixed, dissolved salt needs recovery, reset cancels old action; 16 germination conditions',{timeout:90000},async()=>{
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
 try{browser=await require('playwright')[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.SCIENCE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true,reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const origin='http://127.0.0.1:'+server.address().port;
 await page.goto(origin+'/mixture-separation/');const state=()=>page.evaluate(()=>({groups:__mixtureModel.groups(),left:__mixtureModel.remaining().map(s=>s.id),done:__mixtureModel.complete()}));
 const conserved=async()=>{const s=await state();assert.deepEqual([...s.groups.flatMap(g=>g.ids),...s.left].sort(),['bean','foam','iron','salt','sand']);assert.equal(new Set([...s.groups.flatMap(g=>g.ids),...s.left]).size,5);};
 const tool=async(id)=>{await page.locator('#'+id+'Btn').tap();await page.waitForFunction(()=>!__mixtureModel.isActing());await conserved();};
 for(const [mesh,ids]of [[.2,[]],[.35,['iron']],[.45,['iron','salt']],[.6,['iron','salt','sand']],[7,['iron','salt','sand','foam']],[9,[]]]){await page.locator('#resetBtn').tap();await page.evaluate(m=>__mixtureModel.setMesh(m),mesh);await tool('sieve');const s=await state();assert.equal(s.groups.length,ids.length?1:0);if(ids.length)assert.deepEqual(s.groups[0].ids,ids);assert.equal(s.done,false);}
 await page.locator('#resetBtn').tap();await page.evaluate(()=>__mixtureModel.setMesh(.6));await tool('sieve');await tool('water');assert.doesNotMatch(await page.locator('#stageCaption').textContent(),/소금/);
 await page.locator('#resetBtn').tap();await page.evaluate(()=>__mixtureModel.setMesh(.6));await tool('sieve');assert.equal(await page.locator('#trayGroup .tray-box').count(),1);await page.locator('.experiment-layout').screenshot({path:path.join(out,'mixture-shared-fraction-'+engine+'.png')});
 await page.locator('[data-open-group]').tap();await conserved();assert.deepEqual((await state()).left,['iron','salt','sand']);await tool('magnet');await tool('water');assert.equal((await state()).groups.find(g=>g.ids.includes('salt')).dissolved,true);assert.equal((await state()).done,false);
 await page.locator('[data-open-group]').tap();await page.evaluate(()=>__mixtureModel.setMesh(7));await tool('sieve');assert.equal((await state()).done,false);await page.locator('.experiment-layout').screenshot({path:path.join(out,'mixture-salt-solution-'+engine+'.png')});
 await page.locator('[data-recover-group]').tap();await conserved();assert.equal((await state()).done,true);assert.match(await page.locator('#stageBadge').textContent(),/회수 완료/);
 for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:width>=1024?768:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);}
 await page.setViewportSize({width:1024,height:768});await page.emulateMedia({reducedMotion:'no-preference'});await page.reload();await page.locator('#magnetBtn').tap();await page.locator('#resetBtn').tap();await page.waitForTimeout(1500);assert.equal((await state()).groups.length,0);assert.equal((await state()).left.length,5);
 await page.goto(origin+'/seed-germination/');for(let bits=0;bits<16;bits++){const c={water:!!(bits&1),warm:!!(bits&2),air:!!(bits&4),light:!!(bits&8)};const s=await page.evaluate(c=>{__seedModel.setConditions(c);__seedModel.setProgress(1);return {germinates:__seedModel.germinates(),conditions:__seedModel.conditions(),phase:__seedModel.stageName(1)};},c);assert.equal(s.germinates,c.water&&c.warm&&c.air);assert.deepEqual(s.conditions,c);if(bits===7||bits===15){assert.equal(await page.locator('[data-part=root]').evaluate(e=>getComputedStyle(e).fill),'rgb(255, 247, 230)');assert.equal(await page.locator('[data-part=leaf]').evaluate(e=>getComputedStyle(e).fill),'rgb(15, 23, 42)');}if(bits===7||bits===15)await page.locator('.experiment-layout').screenshot({path:path.join(out,'seed-'+(c.light?'light':'dark')+'-'+engine+'.png')});}
 assert.deepEqual(errors,[]);console.log(engine+': sieve groups at six mesh sizes; full re-separation and salt recovery; 16 seed states passed');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
