const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab');
test('device tools: calibrated length, timer, waveform, opt-in capture, stop, denial, records and tablet layout',{timeout:180000},async()=>{
 const {chromium}=require('playwright'),errors=[];
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.SCIENCE_BROWSER,headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
  const page=await browser.newPage({viewport:{width:1024,height:768}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  const load=async slug=>{await page.goto(`http://127.0.0.1:${server.address().port}/${slug}/`);await page.waitForFunction(()=>!!window.__digitalInquiry);};
  await load('measurement');assert.deepEqual(await page.evaluate(()=>window.__digitalInquiry.snapshot().microphoneTracks),[]);
  assert(await page.locator('[data-length-record]').isDisabled());
  await page.locator('[data-calibration]').fill('200');await page.locator('[data-calibrate]').click();await page.locator('[data-length]').fill('100');assert.equal(await page.locator('[data-length-value]').textContent(),'2.50 cm');await page.locator('[data-length-record]').click();
  await page.locator('[data-timer-start]').click();await page.waitForFunction(()=>parseFloat(document.querySelector('[data-time]').textContent)>=.12);await page.locator('[data-timer-stop]').click();const rows=await page.evaluate(()=>window.__digitalInquiry.records());assert.equal(rows[0].value,2.5);assert(rows[1].value>=.12&&rows[1].value<10);assert.equal(rows[1].unit,'s');
  for(const width of [1366,1024,820,768,390]){await page.setViewportSize({width,height:width>=1024?768:1024});await page.waitForFunction(()=>document.querySelector('[data-length-record]').disabled);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'overflow '+width);const sizes=await page.locator('.digital-inquiry button').evaluateAll(bs=>bs.map(b=>b.getBoundingClientRect().height));assert(sizes.every(h=>h>=43));}
  await page.setViewportSize({width:1024,height:768});
  const download=page.waitForEvent('download');await page.locator('[data-export]').click();const artifact=await download;const data=JSON.parse(fs.readFileSync(await artifact.path(),'utf8'));assert.equal(data.records.length,2);assert.equal(data.records[0].unit,'cm');
  await page.locator('[data-signal]').click();await page.waitForFunction(()=>{const s=window.__digitalInquiry.snapshot();return s.active&&s.last&&Math.abs(s.last.rms-.3/Math.sqrt(2))<.015;});let snap=await page.evaluate(()=>window.__digitalInquiry.snapshot());assert.equal(snap.last.kind,'연습 신호');assert(Math.abs(snap.last.rms-.3/Math.sqrt(2))<.02);assert(Math.abs(snap.last.peak-440)<snap.last.resolution);assert.deepEqual(snap.microphoneTracks,[]);
  await page.locator('[data-amplitude]').selectOption('0.6');await page.locator('[data-frequency]').selectOption('880');await page.waitForFunction(()=>Math.abs((window.__digitalInquiry.snapshot().last?.rms||0)-.6/Math.sqrt(2))<.015);snap=await page.evaluate(()=>window.__digitalInquiry.snapshot());assert(Math.abs(snap.last.peak-880)<snap.last.resolution);await page.locator('[data-audio-record]').click();assert.equal((await page.evaluate(()=>window.__digitalInquiry.records())).length,4);
  await page.locator('[data-audio-stop]').click();assert.equal((await page.evaluate(()=>window.__digitalInquiry.snapshot())).active,false);
  await page.locator('[data-microphone]').click();await page.waitForFunction(()=>window.__digitalInquiry.snapshot().microphoneTracks[0]==='live');await page.locator('[data-audio-stop]').click();assert.deepEqual((await page.evaluate(()=>window.__digitalInquiry.snapshot())).microphoneTracks,[]);
  await page.locator('[data-microphone]').click();await page.waitForFunction(()=>window.__digitalInquiry.snapshot().active);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal((await page.evaluate(()=>window.__digitalInquiry.snapshot())).active,false);
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('denied','NotAllowedError');};});await page.locator('[data-microphone]').click();await page.waitForFunction(()=>document.querySelector('[data-audio-status]').textContent.includes('허용되지'));assert.equal((await page.evaluate(()=>window.__digitalInquiry.snapshot())).active,false);
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{window.finishPending=()=>resolve({getTracks:()=>[{stop:()=>{window.pendingStopped=true;}}]});});});await page.locator('[data-microphone]').click();await page.waitForFunction(()=>!!window.finishPending);await page.locator('[data-audio-stop]').click();await page.evaluate(()=>window.finishPending());await page.waitForFunction(()=>window.pendingStopped===true);assert.equal((await page.evaluate(()=>window.__digitalInquiry.snapshot())).active,false);
  if(process.env.SCIENCE_CAPTURE){const dir=path.resolve(root,'../../../docs/science-lab-audit-2026-09-20/required-gap-screenshots');fs.mkdirSync(dir,{recursive:true});await page.locator('.digital-inquiry').screenshot({path:path.join(dir,'digital-measurement-1024.png')});}
  await page.locator('[data-clear]').click();assert.equal((await page.evaluate(()=>window.__digitalInquiry.records())).length,0);
  await load('wave-transfer');assert.equal(await page.locator('[data-timer-start]').count(),0);await page.locator('[data-signal]').click();await page.waitForFunction(()=>window.__digitalInquiry.snapshot().last?.rms>.1);for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}await page.locator('[data-audio-stop]').click();assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
