// Independent physical expectations, not an expected answer copied from the app under test.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),out=path.resolve(__dirname,'../docs/science-lab-audit-2026-09-20/content-validity');
const near=(a,b,msg='')=>assert.ok(Math.abs(a-b)<1e-7*Math.max(1,Math.abs(b)),msg+': '+a+' != '+b);
for(const engine of ['chromium','webkit'])test(engine+': scientific content and boundary regressions',{timeout:180000},async()=>{
 const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const counts={};
 try{browser=await require('playwright')[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.SCIENCE_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.clock.install();const go=s=>page.goto('http://127.0.0.1:'+server.address().port+'/'+s+'/');
 const shot=async s=>{fs.mkdirSync(out,{recursive:true});await page.locator('.experiment-layout').screenshot({path:path.join(out,s+'-'+engine+'.png')});};
 await go('land-sea');const salts=await page.evaluate(()=>{const m=__landSeaModel,rows=[];for(const water of ['sea','river','tap'])for(const grams of [100,200])rows.push({water,grams,a:m.analyseSalt({...m.state,water,grams})});return rows;});
 for(const {water,grams,a}of salts){near(a.salt,grams*{sea:.035,river:.0002,tap:.0001}[water]);near(a.salt+a.evaporated,grams);}counts.evaporation=salts.length;
 const samples=await page.evaluate(()=>{const m=__landSeaModel,rs=[];m.state.dots=10;for(let seed=1;seed<=2000;seed++){m.state.seed=seed;m.state.drops=[];rs.push({seed,...m.analyseArea()});}return rs;});for(const a of samples)assert.equal(a.verdict,a.seaAll>6?'sea-more':a.seaAll<4?'land-more':'even');assert.equal(new Set(samples.map(a=>a.verdict)).size,3);counts.samples=samples.length;
 for(const expected of ['sea-more','land-more','even']){const seed=samples.find(a=>a.verdict===expected).seed;await page.evaluate(seed=>{__landSeaModel.setMode('area');__landSeaModel.set('dots',10);__landSeaModel.setSeed(seed);},seed);await page.locator('[data-prediction="'+expected+'"]').tap();await page.evaluate(()=>__landSeaModel.runToEnd(1));assert.match(await page.locator('#predictionResult').textContent(),/맞았습니다/);const text=await page.locator('#stageVerdict').textContent();assert.match(text,expected==='sea-more'?/바다에 더 많이/:expected==='land-more'?/육지에 더 많이/:/반반/);}
 await page.evaluate(()=>{__landSeaModel.setMode('salt');__landSeaModel.set('water','sea');__landSeaModel.set('grams',100);__landSeaModel.runToEnd(1);});assert.equal((await page.locator('#valueB').textContent()).trim(),'96.5 g');await shot('evaporation-balance');
 await go('recrystallise');const crystals=await page.evaluate(()=>{const rows=[];for(const key of ['kno3','nacl'])for(const w of [50,100,200])for(const T1 of [40,60,80,100])for(const T2 of [0,20,40,60])for(const imp of [0,5,10]){const a=__crystalModel.analyse(key,w,T1,T2,imp);rows.push({key,w,T1,T2,imp,a,initial:__crystalModel.outAt(T1,a),final:__crystalModel.outAt(T2,a)});}return rows;});
 const sol={kno3:{0:13.3,20:31.6,40:63.9,60:110,80:169,100:246},nacl:{0:35.7,20:36,40:36.6,60:37.3,80:38.4,100:39.8}};
 for(const {key,w,T1,T2,imp,a,initial,final}of crystals){assert.equal(a.T1,T1);assert.equal(a.T2,T2);const c=Math.max(0,(sol[key][T1]-sol[key][T2])*w/100);near(a.crystals,c);near(final.crystals,c);near(initial.crystals,0);near(initial.imp,Math.max(0,imp-.12*w));near(a.dissolved,sol[key][T1]*w/100);if(c===0)assert.equal(a.verdict,'none');}counts.recrystallization=crystals.length;
 for(const [start,end,imp]of [[40,40,0],[40,60,0],[40,60,10],[80,20,0]]){await page.evaluate(([s,e,imp])=>{__crystalModel.setWater(50);__crystalModel.setHot(s);__crystalModel.setCold(e);__crystalModel.setDirt(imp);},[start,end,imp]);for(const choice of ['pure','none','slight','dirty']){await page.locator('[data-prediction="'+choice+'"]').tap();await page.evaluate(()=>__crystalModel.check());assert.equal(/맞았습니다/.test(await page.locator('#predictionResult').textContent()),choice===(end>=start?'none':'pure'));}}
 await page.evaluate(()=>{__crystalModel.setHot(40);__crystalModel.setCold(60);__crystalModel.setDirt(0);__crystalModel.check();});assert.doesNotMatch(await page.locator('#elementaryExplanation').textContent(),/100% 순수/);assert.match(await page.locator('#mainGroup').textContent(),/0.0 g \(용해도가 줄지 않음\)/);assert.match(await page.locator('#stageCaption').textContent(),/물의 질량/);await page.evaluate(()=>__crystalModel.runToEnd());await shot('recrystallization-no-crystal');
 await go('body-organs');assert.deepEqual(await page.evaluate(()=>__organModel.SYSTEMS.excr.organs.map(o=>o.n)),['콩팥','오줌관','방광','요도']);await page.evaluate(()=>{__organModel.setSys('excr');__organModel.runToEnd();});assert.match(await page.locator('#graphGroup').textContent(),/요도/);await shot('urinary-path');
 await go('living-things');await page.evaluate(()=>{__livingThingsModel.setMode('sort');__livingThingsModel.set('rule','fur');__livingThingsModel.runToEnd(1);});const sort=await page.locator('#elementaryExplanation').textContent();assert.match(sort,/수가 달라도/);assert.doesNotMatch(sort,/쓸모가 없/);const animals=await page.evaluate(()=>__livingThingsModel.BEINGS);assert.match(animals.camel.traits.join(' '),/속눈썹/);assert.doesNotMatch(JSON.stringify(animals),/헤엄치지도|털이 얇아 추위를 견디지/);
 await go('rock-layers');assert.ok(await page.evaluate(()=>__layerModel.GRAINS.find(g=>g.id==='mud').mm<.0625));assert.doesNotMatch(await page.locator('#speedNote').textContent(),/제곱|16배|1\/16/);assert.match(await page.locator('#speedNote').textContent(),/실제 속도나 속도 비율이 아닙니다/);
 await go('body-systems');const breaths=await page.evaluate(()=>Object.keys(__bodyModel.ACTS).map(k=>__bodyModel.derive(k)));for(const a of breaths){near(a.co*1000,a.d.hr*a.d.sv);near((.21-a.feO2)*a.ve*1000,a.d.vo2);assert.ok(a.feO2>0&&a.feO2<.21);}counts.respiration=breaths.length;
 await go('gravity-motion');const impacts=await page.evaluate(()=>{const rs=[];for(const h of Object.keys(__gravityModel.DROPS))for(const f of Object.keys(__gravityModel.FLOORS))rs.push(__gravityModel.impactCalc(h,f));return rs;});for(const a of impacts){near((a.F-a.W)*a.dt,a.p);near((a.F-a.W)*a.d,.5*(a.W/9.8)*a.v*a.v);near(a.ratio,1+a.h/a.d);assert.ok(a.F>a.W);}counts.impacts=impacts.length;
 await go('nutrient-detection');const colour=await page.evaluate(()=>__nutrientModel.REAGENTS.biuret);assert.equal(colour.color,'#38bdf8');assert.equal(colour.result,'#7e22ce');await page.evaluate(()=>{__nutrientModel.setMode('reagent');__nutrientModel.set('reagent','biuret');__nutrientModel.runToEnd(1);});await shot('biuret-blue-control');
 await go('mass-ratio');const mass=await page.evaluate(()=>{const rs=[];for(let m=0;m<=10;m++)for(let o=0;o<=10;o++)rs.push({m,o,a:__massModel.react(m,o)});return rs;});for(const {m,o,a}of mass){near(a.product,Math.min(m/3,o/2)*5);near(a.before,a.after);near(a.before,m+o);assert.ok(a.mgLeft>=-1e-9&&a.oxLeft>=-1e-9);}counts.massBalance=mass.length;
 await go('seawater');const sea=await page.evaluate(()=>{const rs=[];for(const T of [0,10,20,30])for(const S of [32,35,38])for(const W of [0,5,10])rs.push(__seaModel.analyse(T,S,W));return rs;});for(const a of sea){near(a.grams.reduce((s,v)=>s+v,0),a.S);assert.equal(a.verdict,a.S>35?'heavier':a.S<35?'lighter':'same');}counts.seawater=sea.length;
 await go('moon-phases');const phases=await page.evaluate(()=>[0,29.53/4,29.53/2,29.53*3/4,29.53].map(d=>__moonModel.litFraction(__moonModel.elongationDeg(d))));phases.forEach((v,i)=>near(v,[0,.5,1,.5,0][i]));counts.moon=5;
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'independent-regressions-'+engine+'.json'),JSON.stringify({engine,counts,pageErrors:errors},null,2));console.log({engine,...counts});
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
