const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab');
test('independent checks: current/voltage, friction, collision conservation, survival proportions',{timeout:90000},async()=>{
 let browser;const errors=[];const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{browser=await require('playwright').chromium.launch({headless:true,executablePath:process.env.SCIENCE_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1024,height:768}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const go=slug=>page.goto('http://127.0.0.1:'+server.address().port+'/'+slug+'/');
 await go('ohms-law');const circuits=await page.evaluate(()=>{const out=[];for(const w of ['series','parallel'])for(const v of [3,6,12])for(const r1 of [5,10,20])for(const r2 of [5,10,20]){window.__ohmModel.set(v,r1,r2,w);out.push({s:window.__ohmModel.state(),a:window.__ohmModel.analyse()});}return out;});
 const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
 for(const {s,a}of circuits){const expected=s.wiring==='series'?s.R1+s.R2:1/(1/s.R1+1/s.R2);near(a.R,expected);near(a.I,s.V/expected);if(s.wiring==='series'){near(a.v1+a.v2,s.V);near(a.i1,a.i2);}else{near(a.i1+a.i2,a.I);near(a.v1,s.V);near(a.v2,s.V);}}
 await go('force-motion');const forces=await page.evaluate(()=>{const out=[];for(const floor of ['ice','wood','rubber'])for(const f of [0,2,8,20])for(const m of [1,4,10])for(const v of [0,2])out.push({f,m,v,floor,a:window.__forceModel.analyse(f,m,v,floor)});return out;});for(const {f,m,v,floor,a}of forces){const frictionLimit={ice:.05,wood:.2,rubber:.4}[floor]*m*10;near(a.friction,v?frictionLimit:Math.min(f,frictionLimit));near(a.accel,v?(f-frictionLimit)/m:Math.max(0,(f-frictionLimit)/m));if(!v&&f<=frictionLimit)assert.equal(a.motion,'rest');}
 await go('collision');const collisions=await page.evaluate(()=>{const out=[];const model=Object.keys(window).filter(k=>k.startsWith('__')&&k.endsWith('Model')).map(k=>window[k]).find(m=>typeof m.analyse==='function');for(const k of ['elastic','partial','stick'])for(const m1 of [1,2,5])for(const m2 of [1,2,5])for(const v of [1,3,6])out.push(model.analyse(k,m1,m2,v,0));return out;});for(const a of collisions){near(a.pBefore,a.pAfter);assert.ok(a.kAfter<=a.kBefore+1e-8);if(a.kind==='elastic')near(a.kBefore,a.kAfter);if(a.kind==='stick')near(a.after1,a.after2);}
 await go('geologic-time');for(const [forest,remaining,answer]of [['even',80,'most'],['two',50,'half'],['dominant',10,'gone'],['mono',0,'gone']]){
  await page.evaluate(f=>{window.__geoTimeModel.setMode('diversity');window.__geoTimeModel.set('forest',f);},forest);assert.equal(await page.locator('[data-prediction="most"]').textContent(),'80 % 남음');await page.locator('[data-prediction="'+answer+'"]').click();const result=await page.evaluate(()=>{window.__geoTimeModel.runToEnd();return window.__geoTimeModel.analyse();});assert.equal(result.remaining,remaining);assert.match(await page.locator('#predictionResult').textContent(),/예상이 맞/);assert.doesNotMatch(await page.locator('#mainGroup').textContent(),/80 % 넘게|마리/);
 }
 console.log({circuits:circuits.length,forces:forces.length,collisions:collisions.length,survival:4});assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
