const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab');
for(const engine of ['chromium','webkit'])test(`${engine}: battery prediction, apparatus continuity and electromagnet controls`,{timeout:90000},async()=>{
 const pw=require('playwright'),errors=[];let browser;
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{
  browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.SCIENCE_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
  const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  await page.goto('http://127.0.0.1:'+server.address().port+'/circuit-bulbs/');await page.waitForFunction(()=>!!window.__circuitModel);
  const tap=s=>page.locator(s).tap(),range=async(id,value)=>{await page.locator('#'+id).fill(String(value));await page.locator('#'+id).dispatchEvent('input');},grade=()=>page.locator('#predictionResult').getAttribute('data-correct');
  await tap('[data-prediction="same"]');await tap('#checkBtn');assert.equal(await grade(),null,'baseline must not mark same correct');assert.match(await page.locator('#predictionResult').textContent(),/비교 기준/);
  await range('circuitBatteryRange',2);assert.equal(await page.locator('#resultContent').isVisible(),false);assert.match(await page.locator('#stageCaption').textContent(),/두 개/);await tap('#checkBtn');assert.equal(await grade(),'false');
  for(const answer of ['brighter','same','dimmer']){await tap(`[data-prediction="${answer}"]`);assert.equal(await grade(),null);assert.equal(await page.locator('#resultContent').isVisible(),false);await tap('#checkBtn');assert.equal(await grade(),String(answer==='brighter'));}
  assert.equal(await page.locator('.battery-cell').count(),2);assert.equal(await page.locator('.battery-jumper').count(),1);
  const out=path.resolve(__dirname,'../docs/science-lab-audit-2026-09-20/circuit-behavior-screenshots');fs.mkdirSync(out,{recursive:true});await page.locator('.experiment-layout').screenshot({path:path.join(out,engine+'-two-cells.png')});
  await tap('[data-circuit="open"]');assert.equal(await page.locator('[data-prediction].selected').count(),0);assert.equal(await page.locator('.current').count(),0);assert.match(await page.locator('#predictionLegend').textContent(),/끊어진/);await tap('[data-prediction="dimmer"]');await tap('#checkBtn');assert.equal(await grade(),'true');assert.equal(await page.locator('#resultB').textContent(),'꺼짐');
  await tap('[data-mode="magnet"]');assert.equal(await page.locator('[data-prediction].selected').count(),0);await range('magnetBatteryRange',1);await range('coilRange',50);const get=()=>page.evaluate(()=>window.__circuitModel.magnetState());let previous=await get();assert.equal(previous.clips,1);
  await range('magnetBatteryRange',2);assert.ok((await get()).clips>previous.clips);previous=await get();await range('coilRange',200);assert.ok((await get()).clips>previous.clips);previous=await get();
  assert.equal(await page.locator('.coil-front').count(),13);assert.equal(await page.locator('.coil-back').count(),13);assert.equal(await page.locator('.attracted').count(),8);
  await tap('#checkBtn');await tap('[data-direction="reverse"]');assert.equal(await page.locator('#resultContent').isVisible(),false);let reversed=await get();assert.equal(reversed.leftPole,previous.rightPole);assert.equal(reversed.rightPole,previous.leftPole);assert.equal(reversed.clips,previous.clips);assert.deepEqual(await page.locator('.battery-cell').evaluateAll(es=>es.map(e=>e.dataset.positive)),['right','right']);
  await tap('#compareBtn');await page.locator('.experiment-layout').screenshot({path:path.join(out,engine+'-electromagnet.png')});await tap('#powerBtn');assert.equal((await get()).clips,0);assert.equal(await page.locator('.current').count(),0);assert.equal(await page.locator('.attracted').count(),0);assert.equal(await page.locator('.permanent-clip').count(),6);assert.equal(await page.locator('.fallen').count(),8);await tap('#checkBtn');assert.equal(await page.locator('#resultA').textContent(),'0개');
  for(const [width,height]of [[768,1024],[1180,820],[1366,768]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);const clipped=await page.locator('.circuit-svg').evaluate(svg=>{const v=svg.viewBox.baseVal;return [...svg.querySelectorAll('text')].filter(t=>{const b=t.getBBox();return b.x<0||b.y<0||b.x+b.width>v.width||b.y+b.height>v.height;}).map(t=>t.textContent);});assert.deepEqual(clipped,[]);}
  assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
