const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),out=path.resolve(process.env.SCIENCE_TEST_ARTIFACTS || path.resolve(__dirname,'../docs/science-lab-audit-2026-09-20'), 'content-validity');
for(const engine of ['chromium','webkit'])test(engine+': readable tablet controls and current exam-bank cache',{timeout:90000},async()=>{
 fs.mkdirSync(out,{recursive:true}); const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');fs.readFile(f,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];let scenarios=0;
 try{browser=await require('playwright')[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.SCIENCE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const origin='http://127.0.0.1:'+server.address().port;
 for(const slug of ['body-organs','nutrient-detection']){await page.goto(origin+'/'+slug+'/');const selector=slug==='body-organs'?'button[data-sys]':'button[data-mode]';const choices=await page.locator(selector).count();for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:width>820?768:1024});for(let i=0;i<choices;i++){await page.locator(selector).nth(i).tap();const result=await page.evaluate(()=>{const selectors='.control-panel .pick-buttons.cols4 button,.control-panel .prediction-buttons button,.control-panel .mode-buttons button';return{overflow:document.documentElement.scrollWidth>innerWidth+2,buttons:[...document.querySelectorAll(selectors)].filter(n=>n.getClientRects().length).map(n=>({text:n.textContent.trim(),width:n.getBoundingClientRect().width,height:n.offsetHeight,wrap:getComputedStyle(n).wordBreak,overflow:n.scrollWidth>n.clientWidth+2}))};});assert.equal(result.overflow,false,slug+' '+width);for(const b of result.buttons){assert.ok(b.width>=90,slug+' '+b.text+' width '+b.width);assert.ok(b.height>=44);assert.equal(b.wrap,'keep-all');assert.equal(b.overflow,false,slug+' '+b.text);}scenarios++;}}
 await page.setViewportSize({width:1024,height:768});await page.locator('.control-panel').screenshot({path:path.join(out,slug+'-readable-controls-'+engine+'.png')});}
 await page.goto(origin+'/exam-review.html');await page.waitForSelector('.exam-answers');const urls=await page.locator('script[src*="exam-bank"]').evaluateAll(ns=>ns.map(n=>n.src));assert.equal(urls.length,6);assert(urls.every(u=>new URL(u).searchParams.get('v')==='4'));assert.deepEqual(errors,[]);console.log(engine+': '+scenarios+' control layouts and six current question data resources passed');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
