const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),bank=require(path.join(root,'exam-bank.js')),map=require(path.join(root,'curriculum-map.js'));
test('all 194 editorial revisions match the bank and retain distinct misconception choices',()=>{
 const changes=require('../scripts/science-exam-choice-review.cjs').split('\n');assert.equal(changes.length,194);
 for(const line of changes){const [id,...fields]=line.split('|'),q=bank.questions.find(q=>q.id===id);assert(q,id);assert.equal(new Set(q.choices).size,3,id);for(const text of fields.length===2?fields:fields.slice(1,4))assert(q.choices.includes(text),id);if(fields.length===5){assert.equal(q.question,fields[0]);assert.equal(q.why,fields[4]);}}
 const counts=[0,0,0];bank.questions.forEach(q=>counts[q.answer]++);assert(counts.every(n=>n>50));assert(bank.questions.slice(3,20).some((q,i)=>q.answer!==bank.questions[i].answer),'answer positions must not repeat every three items');
 const wrong=bank.questions.flatMap(q=>q.choices.filter((_,i)=>i!==q.answer)).join('\n');assert(!/힘은 물체의 색만|모든 물체가 녹아서|태양이 밤마다 폭발|모든 생물을 한 종류|기체는 물질이 아니다/.test(wrong));
 for(const slug of Object.keys(map)){const html=fs.readFileSync(path.join(root,slug,'index.html'),'utf8');assert.equal((html.match(/href="[^" ]*science-reading.css/g)||[]).length,1,slug);}
});
test('clean question sheet, CSAT reading font, all-grade layouts and original-app typography',{timeout:120000},async()=>{
 const {chromium}=require('playwright');const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({headless:true,executablePath:process.env.SCIENCE_BROWSER});const page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const host=new URL(r.request().url()).hostname;r[host==='127.0.0.1'||process.env.SCIENCE_LIVE_FONTS&&['fonts.googleapis.com','fonts.gstatic.com'].includes(host)?'continue':'abort']();});const origin='http://127.0.0.1:'+server.address().port;
  await page.goto(origin+'/exam-review.html');await page.waitForSelector('.exam-answers');
  if(process.env.SCIENCE_LIVE_FONTS){const faces=await page.evaluate(async()=>{const fonts=await document.fonts.load('400 16px "Noto Serif KR"','힘을 주는 방향에 따라 속력이 줄어들 수 있다');return fonts.map(f=>({family:f.family,status:f.status}));});assert(faces.length>0,'web font must actually load');assert(faces.every(f=>f.status==='loaded'));console.log('Noto Serif KR: browser font loaded');}
  const initial=await page.evaluate(()=>{const h=document.querySelector('h1'),q=document.querySelector('.exam-question'),b=document.querySelector('.exam-answers button');return{headingWidth:h.getBoundingClientRect().width,cardBorder:getComputedStyle(q).borderTopWidth,choiceBorder:getComputedStyle(b).borderTopWidth,font:getComputedStyle(b).fontFamily,before:getComputedStyle(b,'::before').content,top:document.querySelector('.exam-grades').getBoundingClientRect().top};});assert(initial.headingWidth<=1);assert.equal(initial.cardBorder,'0px');assert.equal(initial.choiceBorder,'0px');assert.match(initial.font,/Noto Serif KR/);assert(initial.top<100);assert(initial.before.includes('①'));
  for(const grade of bank.grades){await page.locator('[data-exam-grade="'+grade+'"]').click();await page.locator('[data-exam-answer="0"]').click();for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:width>=1024?768:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,grade+' '+width);assert.match(await page.locator('.exam-feedback').evaluate(n=>getComputedStyle(n).fontFamily),/Noto Serif KR/);}}
  if(process.env.SCIENCE_CAPTURE){await page.goto(origin+'/exam-review.html?grade='+encodeURIComponent('초3'));await page.waitForSelector('.exam-answers');await page.evaluate(()=>document.fonts.ready);await page.setViewportSize({width:1024,height:768});const dir=path.resolve(root,'../../../docs/science-lab-audit-2026-09-20/exam-editorial-screenshots');fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,'question-sheet.png'),fullPage:true});}
  for(const slug of ['light-shadow','cell-structure','earth-system']){await page.goto(origin+'/'+slug+'/');await page.waitForSelector('.quiz-card',{state:'attached'});const actual=await page.evaluate(()=>({question:getComputedStyle(document.querySelector('.quiz-card h3')).fontFamily,choice:getComputedStyle(document.querySelector('.quiz-options label')).fontFamily,explanation:getComputedStyle(document.querySelector('.answer-explanation')).fontFamily,control:getComputedStyle(document.querySelector('.answer-button')).fontFamily}));for(const key of ['question','choice','explanation'])assert.match(actual[key],/Noto Serif KR/,slug+' '+key);assert(!actual.control.includes('Noto Serif KR'));}
  assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
