const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),bank=require(path.join(root,'exam-bank.js')),map=require(path.join(root,'curriculum-map.js')),inv=require('../scripts/audit_science_curriculum.cjs');
test('exam bank covers all 220 common standards with valid answers and grade-specific questions',()=>{
 const source=inv.sections.flatMap(s=>s.standards).filter(s=>/^(4과|6과|9과|10통과)/.test(s.code));assert.equal(source.length,220);assert.equal(bank.questions.length,241);assert.equal(new Set(bank.questions.map(q=>q.id)).size,241);assert.deepEqual([...new Set(bank.questions.map(q=>q.code))].sort(),source.map(s=>s.code).sort());
 for(const q of bank.questions){assert.equal(q.choices.length,3);assert.equal(new Set(q.choices).size,3);assert(q.answer>=0&&q.answer<3);assert(q.why.length>20);assert(bank.grades.includes(q.grade));assert(bank.units[q.unit].standards.some(s=>s.code===q.code));if(q.host)assert(map[q.host].grades.includes(q.grade),q.id+' host grade');if(q.data)for(const r of q.data.rows)assert.equal(r.length,q.data.headers.length);}
 const correct=id=>{const q=bank.questions.find(q=>q.id===id);return q.choices[q.answer];};
 assert.equal(correct('9과05-02'),'0.8 N');assert.equal(correct('9과08-01'),'2.7 g/cm³');assert.equal(correct('9과15-01'),'5 pc');assert.equal(correct('9과16-04'),'4 g');assert.equal(correct('9과16-05'),'10 mL');assert.equal(correct('9과21-04'),'AA:Aa:aa = 1:2:1');assert.equal(correct('10통과2-02-06'),'30%');assert.equal(correct('9과19-01@motion'),'9 m');assert.equal(correct('6과13-01@day'),'12시·15시');
 assert.match(correct('10통과2-01-03'),/전자 잃음은 산화/);assert.match(correct('9과14-03'),/병렬/);assert.match(correct('6과15-03'),/극이 바뀐다/);
 const elementary=bank.questions.filter(q=>q.grade.startsWith('초'));for(const q of elementary)assert(!/pH|합성.?저항|스넬|엔탈피|산화수/.test(q.question));
});
test('all exam answers, filters, persistence, charts, app integration and tablet screens',{timeout:240000},async()=>{
 const {chromium}=require('playwright'),errors=[];let browser;
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{browser=await chromium.launch({headless:true,executablePath:process.env.SCIENCE_BROWSER});const page=await browser.newPage({viewport:{width:1024,height:768}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const origin='http://127.0.0.1:'+server.address().port;
  await page.goto(origin+'/exam-review.html?grade=없는학년&unit=없는단원');await page.waitForFunction(()=>!!document.querySelector('.exam-widget')?.examController);let count=0;
  for(const grade of bank.grades){await page.locator('[data-exam-grade="'+grade+'"]').click();const expected=bank.questions.filter(q=>q.grade===grade);assert.deepEqual(await page.locator('.exam-widget').evaluate(w=>w.examController.ids()),expected.map(q=>q.id));for(let n=0;n<expected.length;n++){const q=expected[n];assert.equal(await page.locator('.exam-question').getAttribute('data-exam-id'),q.id);for(let i=0;i<3;i++){await page.locator('[data-exam-answer="'+i+'"]').click();assert.equal(await page.locator('.exam-feedback').getAttribute('data-correct'),String(i===q.answer));assert((await page.locator('.exam-feedback').textContent()).includes(q.why));}if(q.data)assert.equal(await page.locator('.exam-data tbody tr').count(),q.data.rows.length);if(n<expected.length-1)await page.locator('[data-exam-next]').click();count++;}
   assert(await page.locator('[data-exam-next]').isDisabled());await page.locator('.exam-reset').click();assert.equal(await page.locator('.exam-feedback').textContent(),'');
  }
  for(const[unit,m]of Object.entries(bank.units)){await page.locator('[data-exam-grade="'+m.grade+'"]').click();await page.locator('.exam-filter select').selectOption(unit);assert.deepEqual(await page.locator('.exam-widget').evaluate(w=>w.examController.ids()),bank.questions.filter(q=>q.unit===unit).map(q=>q.id));}
  await page.locator('[data-exam-grade="중1"]').click();await page.locator('[data-exam-answer="1"]').click();const first=await page.locator('.exam-question').getAttribute('data-exam-id');await page.locator('[data-exam-next]').click();await page.locator('[data-exam-prev]').click();assert.equal(await page.locator('.exam-question').getAttribute('data-exam-id'),first);assert.equal(await page.locator('[data-exam-answer="1"]').getAttribute('aria-pressed'),'true');
  for(const unit of ['9과04','6과13','10통과2-01']){await page.goto(origin+'/exam-review.html?grade='+encodeURIComponent(bank.units[unit].grade)+'&unit='+unit);await page.waitForFunction(()=>!!document.querySelector('.exam-widget')?.examController);const qs=bank.questions.filter(q=>q.unit===unit);for(let i=0;i<qs.length;i++){for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:width>=1024?768:1024});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,qs[i].id+' '+width);const bad=await page.locator('.exam-chart').evaluateAll(svgs=>svgs.flatMap(svg=>{const b=svg.getBoundingClientRect();return [...svg.querySelectorAll('text')].filter(t=>{const a=t.getBoundingClientRect();return a.left<b.left-1||a.right>b.right+1||a.top<b.top-1||a.bottom>b.bottom+1;}).map(t=>t.textContent);}));assert.deepEqual(bad,[]);if(process.env.SCIENCE_CAPTURE&&width===1024&&qs[i].data){const dir=path.resolve(root,'../../../docs/science-lab-audit-2026-09-20/exam-review-screenshots');fs.mkdirSync(dir,{recursive:true});await page.locator('.exam-page').screenshot({path:path.join(dir,qs[i].id.replaceAll('@','-')+'.png')});}}if(i<qs.length-1)await page.locator('[data-exam-next]').click();}}
  for(const slug of ['living-things','seasons','diffusion','refraction','senses','cell-membrane']){await page.goto(origin+'/'+slug+'/');await page.waitForSelector('.exam-local');assert.equal(await page.locator('script[src*="exam-bank-elementary"]').count(),0,'bank loads only on opening');await page.locator('.exam-local summary').click();await page.waitForFunction(()=>!!document.querySelector('.exam-widget')?.examController);assert.deepEqual(await page.locator('.exam-widget').evaluate(w=>w.examController.ids()),bank.forApp(slug,map).map(q=>q.id));await page.locator('[data-exam-answer="0"]').click();assert.equal(await page.locator('.quiz-card').count(),4);}
  await page.goto(origin+'/');await page.locator('[data-grade="중3"]').click();assert((await page.locator('#examReviewLink').getAttribute('href')).includes(encodeURIComponent('중3')));await page.locator('[data-grade="고2"]').click();assert(await page.locator('#examReviewLink').isHidden());assert.deepEqual(errors,[]);assert.equal(count,241);console.log(count+' questions / '+count*3+' answer checks / 61 unit filters');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
