const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../learning/inquiry/science-lab'),out=path.resolve(__dirname,'../docs/science-lab-audit-2026-09-20/visual-recheck/verified');fs.mkdirSync(out,{recursive:true});
const plant=Object.values(require(path.join(root,'required-experiments.js')).requiredExperimentModels()).flat().find(s=>s.id==='plant-life-types');
test('plant types: surviving individual is not confused with a new generation',()=>{
 for(const stage of ['first','winter','next'])for(const seed of ['absent','present']){const r=plant.view({stage,seed});assert.equal(r.metrics.annualAlive,stage==='first');assert.equal(r.metrics.perennialAlive,true);assert.equal(r.metrics.newAnnual,stage==='next'&&seed==='present');assert.equal((r.svg.match(/data-root-alive="true"/g)||[]).length,stage==='first'?2:1);}assert.match(plant.view({stage:'next',seed:'present'}).text,/새 개체/);
});
for(const engine of ['chromium','webkit'])test(engine+': biological movement, meaningful observation states and tablet layout',{timeout:150000},async()=>{
 const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');fs.readFile(f,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];const origin='http://127.0.0.1:'+server.address().port;
 try{browser=await require('playwright')[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.SCIENCE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto(origin+'/life-cycle/');await page.waitForFunction(()=>!!window.__requiredExperiments);
 for(const [animal,count]of [['butterfly',4],['mantis',3],['frog',4],['chick',3]]){await page.locator('[data-animal="'+animal+'"]').tap();
  for(let step=0;step<count;step++){await page.locator('[data-life-step="'+step+'"]').tap();assert.equal(await page.evaluate(()=>window.__lifeModel.analyse().step),step);const moving=step>0&&!(animal==='butterfly'&&step===2);const parts=page.locator('#mainGroup [data-life-motion]');assert.equal(await parts.count()>0,moving,animal+' '+step);
   if(moving){const first=await parts.first().evaluate(e=>{e.dataset.persist='true';return getComputedStyle(e).transform;});await page.waitForTimeout(230);const motion=await parts.first().evaluate(e=>{const a=e.getAnimations()[0];const elapsed=a.currentTime;a.currentTime=a.effect.getTiming().duration*.72;return {elapsed,transform:getComputedStyle(e).transform};});assert(motion.elapsed>0,animal+' clock advances');assert.notEqual(motion.transform,first,animal+' visible movement');assert.equal(await parts.first().getAttribute('data-persist'),'true','animation DOM survives frames');
    await page.locator('#lifeMotionBtn').tap();assert.equal(await parts.first().evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const frozen=await parts.first().evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(100);assert.equal(await parts.first().evaluate(e=>getComputedStyle(e).transform),frozen);await page.locator('#lifeMotionBtn').tap();
   }
   await page.locator('.life-focus').screenshot({path:path.join(out,animal+'-'+step+'-'+engine+'.png')});
   for(const width of [1366,1024,820,768]){await page.setViewportSize({width,height:width>=1024?768:1024});const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+2,buttons:[...document.querySelectorAll('.pick-buttons button,.prediction-buttons button,[data-life-step],#lifeMotionBtn')].map(b=>({text:b.innerText,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height,overflow:b.scrollWidth>b.clientWidth+2})),font:parseFloat(getComputedStyle(document.querySelector('.life-feature p')).fontSize)}));assert.equal(state.overflow,false,animal+' '+width);assert(state.font>=15);for(const b of state.buttons){assert(b.w>=44&&b.h>=44,b.text);assert.equal(b.overflow,false,b.text);}}await page.setViewportSize({width:1024,height:768});
  }
 }
 await page.locator('[data-animal="butterfly"]').tap();await page.locator('[data-life-step="1"]').tap();await page.locator('.experiment-layout').screenshot({path:path.join(out,'life-cycle-'+engine+'.png')});
 await page.locator('#runBtn').tap();await page.evaluate(()=>{window.__lifeModel.tick(4.1);window.__lifeModel.render();});assert.equal(await page.evaluate(()=>window.__lifeModel.state.step),1);await page.locator('#runBtn').tap();await page.locator('#resetBtn').tap();assert.equal(await page.evaluate(()=>window.__lifeModel.state.step),0);assert.equal(await page.evaluate(()=>window.__lifeModel.state.prediction),null);
 await page.locator('[data-required-field="stage"]').selectOption('next');await page.locator('[data-required-field="seed"]').selectOption('present');await page.locator('.required-experiments').screenshot({path:path.join(out,'plant-life-types-'+engine+'.png')});
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>!!window.__lifeModel);await page.locator('[data-life-step="1"]').tap();assert.equal(await page.locator('#mainGroup [data-life-motion]').first().evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await page.emulateMedia({reducedMotion:'no-preference'});
 await page.goto(origin+'/heat-transfer/');assert.equal(await page.locator('#flame').evaluate(e=>getComputedStyle(e).display),'none');await page.locator('#heatBtn').click();assert.notEqual(await page.locator('#flame').evaluate(e=>getComputedStyle(e).display),'none');await page.evaluate(()=>{window.__heatModel.advanceSim(100);window.__heatModel.render();});assert(await page.evaluate(()=>window.__heatModel.profile()[0])>20);await page.locator('.experiment-layout').screenshot({path:path.join(out,'heat-transfer-'+engine+'.png')});await page.locator('#heatBtn').click();assert.equal(await page.locator('#flame').evaluate(e=>getComputedStyle(e).display),'none');
 await page.goto(origin+'/acid-base/');for(const [solution,changed]of [['vinegar','blue'],['lemon','blue'],['soap','red'],['cleaner','red']]){await page.locator('[data-solution="'+solution+'"]').click();await page.locator('#dipButton').click();await page.waitForTimeout(900);for(const strip of ['red','blue']){const height=Number(await page.locator('#'+strip+'ChangeClipRect').getAttribute('height'));assert.equal(height>0,strip===changed,solution+' '+strip);}assert.equal(await page.locator('#resultContent').isVisible(),true);}await page.locator('.experiment-layout').screenshot({path:path.join(out,'acid-base-'+engine+'.png')});
 await page.goto(origin+'/flame-ions/');for(const metal of ['li','na','k','ca','cu','sr']){const color=await page.evaluate(m=>{const v=window.__flameIonModel;v.set('metal',m);v.setProgress(.6);return v.METALS[m].hex;},metal);assert(await page.locator('#mainGroup path[fill="'+color+'"]').count()>0);assert.equal(await page.locator('#mainGroup path[fill="'+color+'"]').first().evaluate(e=>getComputedStyle(e).fill),await page.evaluate(hex=>{const e=document.createElement('div');e.style.color=hex;document.body.append(e);const c=getComputedStyle(e).color;e.remove();return c;},color));}await page.locator('.experiment-layout').screenshot({path:path.join(out,'flame-ions-'+engine+'.png')});await page.evaluate(()=>window.__flameIonModel.setProgress(1));assert.match(await page.locator('#stageBadge').textContent(),/시료 소진/);
 await page.goto(origin+'/wave-transfer/');for(const mode of ['transverse','longitudinal'])for(const f of [.5,1,2]){const a=await page.evaluate(({mode,f})=>{const m=window.__waveModel;m.setMode(mode);m.setFreq(f);return m.analyse();},{mode,f});const text=await page.locator('#stageBadge').textContent();assert(text.includes(a.lambda.toFixed(1)));const dimensions=await page.locator('.span-text').allTextContents();assert(dimensions.some(t=>t.includes(a.lambda.toFixed(1))),JSON.stringify({a,dimensions}));}
 assert.deepEqual(errors,[]);console.log(engine+': 14 stages, 56 layouts, motion/pause/reduced-motion, plant identity, heat, 4 litmus and 6 flame colours verified');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
