import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

test("teacher and student school-election browser flow", { skip: process.env.RUN_ELECTION_UI !== "1" }, async (t) => {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const server = spawn(process.execPath, [path.join(here,"school-election-preview.mjs")],
    { env: { ...process.env, SCHOOL_ELECTION_PREVIEW_PORT: "0" }, windowsHide: true, stdio: ["ignore","pipe","pipe"] });
  t.after(() => server.kill());
  const base = await new Promise((resolve,reject) => {
    let output = "";
    const timeout=setTimeout(()=>reject(new Error("Preview server did not start: "+output)),20000);
    server.once("error",reject);server.once("exit",(code)=>{clearTimeout(timeout);reject(new Error("Preview exit "+code));});
    server.stderr.on("data",(chunk)=>{output+=chunk;});
    server.stdout.on("data",(chunk)=>{output+=chunk;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timeout);resolve(match[0]);}});
  });
  const browser = await chromium.launch({ headless:true, ...(process.platform==="win32"?{channel:"chrome"}:{}) });
  t.after(()=>browser.close());
  const screenshots = await mkdtemp(path.join(os.tmpdir(),"school-election-ui-"));
  const menu = await browser.newPage({ javaScriptEnabled:false, viewport:{width:1280,height:960} });
  await menu.goto(base+"/classtools/");
  assert.equal(await menu.getByRole("link",{name:"🗳️ 학급선거",exact:true}).getAttribute("href"),"/vote/?mode=teacher");
  assert.equal(await menu.getByRole("link",{name:"🏫 전교 임원선거",exact:true}).getAttribute("href"),"/school-election/?mode=teacher");
  await menu.locator(".teaching-tools-grid").screenshot({path:path.join(screenshots,"election-buttons.png")});
  await menu.close();
  const teacher=await browser.newPage({viewport:{width:1280,height:1000}});
  const errors=[];teacher.on("pageerror",(e)=>errors.push(e.message));
  await teacher.goto(base+"/preview/as/10");
  await teacher.getByLabel("선거 제목",{exact:true}).fill("2026학년도 전교 임원선거");
  await teacher.getByLabel("후보 이름",{exact:true}).nth(0).fill("6학년 1반 김하나");
  await teacher.getByLabel("후보 이름",{exact:true}).nth(1).fill("6학년 2반 이두리");
  await teacher.getByRole("button",{name:"저장하고 명부 확인하기",exact:true}).click();
  await teacher.getByRole("heading",{name:"선거인 명부 확인",exact:true}).waitFor();
  assert.match(await teacher.locator("#detail").innerText(),/대상 8명/);
  const code=await teacher.locator(".code-panel strong").innerText();
  assert.match(code,/^\d{6}$/);
  await teacher.screenshot({path:path.join(screenshots,"teacher-roster.png"),fullPage:true});
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"명부 확정하고 투표 시작",exact:true}).click();
  await teacher.getByRole("button",{name:"투표 마감하고 개표하기",exact:true}).waitFor();
  assert.equal(await teacher.getByRole("heading",{name:/개표 결과/}).count(),0);
  await teacher.screenshot({path:path.join(screenshots,"teacher-progress.png"),fullPage:true});

  const student=await browser.newPage({viewport:{width:390,height:844}});
  student.on("pageerror",(e)=>errors.push(e.message));
  await student.goto(base+"/preview/as/21");
  await student.goto(base+"/room/");
  await student.getByLabel("방번호",{exact:true}).fill(code);
  await student.getByRole("button",{name:"입장",exact:true}).click();
  await student.getByRole("button",{name:"선택한 후보에게 투표하기",exact:true}).waitFor();
  await student.getByText("기호 1번 · 6학년 1반 김하나",{exact:true}).click();
  assert.equal(await student.locator("input[type=radio]:checked").count(),1);
  await student.screenshot({path:path.join(screenshots,"student-mobile-ballot.png"),fullPage:true});
  assert.ok(await student.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),"No mobile horizontal overflow");
  student.once("dialog",(dialog)=>dialog.accept());
  await student.getByRole("button",{name:"선택한 후보에게 투표하기",exact:true}).click();
  await student.getByText("투표를 완료했습니다. 참여해 주셔서 감사합니다.",{exact:true}).waitFor();
  await student.reload();
  await student.getByText("투표를 완료했습니다. 참여해 주셔서 감사합니다.",{exact:true}).waitFor();

  await teacher.getByRole("button",{name:"새로고침",exact:true}).click();
  await teacher.getByRole("button",{name:"명단 보기",exact:true}).first().click();
  await teacher.getByText("1번 연습학생21 · 완료",{exact:true}).waitFor();
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"투표 마감하고 개표하기",exact:true}).click();
  await teacher.getByRole("heading",{name:"개표 결과 · 담당 교사 확인용",exact:true}).waitFor();
  assert.match(await teacher.locator("#detail").innerText(),/1표/);
  await student.reload();
  await student.getByText("투표를 완료했습니다. 참여해 주셔서 감사합니다.",{exact:true}).waitFor();
  assert.equal(await student.getByRole("heading",{name:"공개된 선거 결과",exact:true}).count(),0);
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"학생들에게 결과 공개",exact:true}).click();
  await teacher.getByRole("heading",{name:"공개된 선거 결과",exact:true}).waitFor();
  await student.reload();
  await student.getByRole("heading",{name:"공개된 선거 결과",exact:true}).waitFor();
  await student.screenshot({path:path.join(screenshots,"student-mobile-results.png"),fullPage:true});
  const downloadPromise=teacher.waitForEvent("download");
  await teacher.getByRole("button",{name:"결과 CSV 저장",exact:true}).click();
  assert.match((await downloadPromise).suggestedFilename(),/결과\.csv$/);
  const guest=await browser.newPage();
  await guest.goto(base+"/school-election/?room="+code);
  await guest.getByRole("link",{name:"메인에서 계정 로그인하기 →",exact:true}).waitFor();
  assert.equal(await guest.locator("#joinForm").isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log("Election screenshots: "+screenshots);
});
