import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

test("teacher and student school-election browser flow", { skip: process.env.RUN_ELECTION_UI !== "1" }, async (t) => {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const server = spawn(process.execPath, [path.join(here,"school-election-preview.mjs")],
    { env: { ...process.env, SCHOOL_ELECTION_PREVIEW_PORT: "0" }, windowsHide: true, stdio: ["ignore","pipe","pipe"] });
  t.after(() => server.kill());
  const base = await new Promise((resolve,reject) => {
    let output = "";
    const timeout=setTimeout(()=>reject(new Error("Preview server did not start: "+output)),20000);
    server.once("error",reject);server.once("exit",(code)=>{clearTimeout(timeout);reject(new Error("Preview exit "+code));});
    server.stderr.on("data",(chunk)=>{output+=chunk;});
    server.stdout.on("data",(chunk)=>{output+=chunk;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timeout);resolve(match[0]);}});
  });
  const browser = await chromium.launch({ headless:true, ...(process.platform==="win32"?{channel:"chrome"}:{}) });
  t.after(()=>browser.close());
  const screenshots = await mkdtemp(path.join(os.tmpdir(),"school-election-ui-"));
  const menu = await browser.newPage({ javaScriptEnabled:false, viewport:{width:1280,height:960} });
  await menu.goto(base+"/classtools/");
  assert.equal(await menu.getByRole("link",{name:"🗳️ 학급선거",exact:true}).getAttribute("href"),"/vote/?mode=teacher");
  assert.equal(await menu.getByRole("link",{name:"🏫 전교 임원선거",exact:true}).getAttribute("href"),"/school-election/?mode=teacher");
  await menu.locator(".teaching-tools-grid").screenshot({path:path.join(screenshots,"election-buttons.png")});
  await menu.close();
  const teacher=await browser.newPage({viewport:{width:1280,height:1000}});
  const errors=[];teacher.on("pageerror",(e)=>errors.push(e.message));
  await teacher.goto(base+"/preview/as/10");
  await teacher.getByLabel("선거 제목",{exact:true}).fill("2026학년도 전교 임원선거");
  await teacher.getByLabel("후보 이름",{exact:true}).nth(0).fill("6학년 1반 김하나");
  await teacher.getByLabel("후보 이름",{exact:true}).nth(1).fill("6학년 2반 이두리");
  await teacher.getByRole("button",{name:"저장하고 명부 확인하기",exact:true}).click();
  await teacher.getByRole("heading",{name:"선거인 명부 확인",exact:true}).waitFor();
  assert.match(await teacher.locator("#detail").innerText(),/대상 8명/);
  const code=await teacher.locator(".code-panel strong").innerText();
  assert.match(code,/^\d{4}$/);
  await teacher.screenshot({path:path.join(screenshots,"teacher-roster.png"),fullPage:true});
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"명부 확정하고 투표 시작",exact:true}).click();
  await teacher.getByRole("button",{name:"투표 마감하고 개표하기",exact:true}).waitFor();
  assert.equal(await teacher.getByRole("heading",{name:/개표 결과/}).count(),0);
  assert.equal(await teacher.getByRole("button",{name:"선거 데이터 삭제",exact:true}).count(),0);
  await teacher.screenshot({path:path.join(screenshots,"teacher-progress.png"),fullPage:true});
  const admin=await browser.newPage({viewport:{width:1280,height:1000}});
  admin.on("pageerror",(e)=>errors.push(e.message));
  await admin.goto(base+"/preview/as/11");
  await admin.getByRole("heading",{name:"학교 전교선거",exact:true}).waitFor();
  await admin.getByRole("button",{name:"참여 현황 보기",exact:true}).waitFor();
  assert.equal(await admin.locator("#electionList .room-card").count(),1);
  assert.equal(await admin.getByRole("button",{name:"선거 데이터 삭제",exact:true}).count(),0);

  const observer=await browser.newPage({viewport:{width:1280,height:1000}});
  observer.on("pageerror",(e)=>errors.push(e.message));
  await observer.goto(base+"/preview/as/12");
  await observer.getByRole("button",{name:"참여 현황 보기",exact:true}).click();
  await observer.getByRole("heading",{name:"투표 참여 현황",exact:true}).waitFor();
  for (const name of ["투표 마감하고 개표하기","설정 수정","선거 데이터 삭제","선택한 후보에게 투표하기"]) {
    assert.equal(await observer.getByRole("button",{name,exact:true}).count(),0);
  }
  await observer.goto(base+"/room/");
  await observer.getByLabel("방번호",{exact:true}).fill(code);
  await observer.getByRole("button",{name:"입장",exact:true}).click();
  await observer.getByRole("heading",{name:"투표 참여 현황",exact:true}).waitFor();
  await observer.getByRole("button",{name:"명단 보기",exact:true}).first().click();
  await observer.getByText("1번 연습학생21 · 미투표",{exact:true}).waitFor();

  const student=await browser.newPage({viewport:{width:390,height:844}});
  student.on("pageerror",(e)=>errors.push(e.message));
  await student.goto(base+"/preview/as/21");
  await student.goto(base+"/room/");
  await student.getByLabel("방번호",{exact:true}).fill(code);
  await student.getByRole("button",{name:"입장",exact:true}).click();
  await student.getByRole("button",{name:"선택한 후보에게 투표하기",exact:true}).waitFor();
  assert.equal(await student.getByRole("heading",{name:"투표 참여 현황",exact:true}).count(),0);
  assert.equal(await student.getByRole("button",{name:"명단 보기",exact:true}).count(),0);
  await student.getByText("기호 1번 · 6학년 1반 김하나",{exact:true}).click();
  assert.equal(await student.locator("input[type=radio]:checked").count(),1);
  await student.screenshot({path:path.join(screenshots,"student-mobile-ballot.png"),fullPage:true});
  assert.ok(await student.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),"No mobile horizontal overflow");
  student.once("dialog",(dialog)=>dialog.accept());
  await student.getByRole("button",{name:"선택한 후보에게 투표하기",exact:true}).click();
  await student.getByText("투표를 완료했습니다.",{exact:true}).waitFor();
  await student.reload();
  await student.getByText("투표를 완료했습니다.",{exact:true}).waitFor();
  await student.getByRole("heading",{name:"투표 참여 현황",exact:true}).waitFor();
  await student.getByRole("button",{name:"명단 보기",exact:true}).first().click();
  await student.getByText("1번 연습학생21 · 완료",{exact:true}).waitFor();
  await student.getByText("2번 연습학생22 · 미투표",{exact:true}).waitFor();
  assert.equal(await student.getByRole("button",{name:"투표 마감하고 개표하기",exact:true}).count(),0);
  assert.ok(await student.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),"No participation-panel mobile overflow");
  await student.screenshot({path:path.join(screenshots,"student-mobile-progress.png"),fullPage:true});
  await observer.getByRole("button",{name:"새로고침",exact:true}).click();
  await observer.getByText("1번 연습학생21 · 완료",{exact:true}).waitFor();
  await observer.getByText("2번 연습학생22 · 미투표",{exact:true}).waitFor();

  const secondStudent=await browser.newPage();
  secondStudent.on("pageerror",(e)=>errors.push(e.message));
  await secondStudent.goto(base+"/preview/as/22");
  await secondStudent.goto(base+"/school-election/?room="+code);
  await secondStudent.getByText("기호 1번 · 6학년 1반 김하나",{exact:true}).click();
  secondStudent.once("dialog",(dialog)=>dialog.accept());
  await secondStudent.getByRole("button",{name:"선택한 후보에게 투표하기",exact:true}).click();
  await secondStudent.getByText("투표를 완료했습니다.",{exact:true}).waitFor();
  await student.bringToFront();
  // The selected class and its names remain visible while the normal ten-second poll updates them.
  await student.getByText("2번 연습학생22 · 완료",{exact:true}).waitFor({timeout:15000});
  await student.getByRole("heading",{name:"3학년 1반 참여 현황",exact:true}).waitFor();

  await teacher.getByRole("button",{name:"새로고침",exact:true}).click();
  await teacher.getByRole("button",{name:"명단 보기",exact:true}).first().click();
  await teacher.getByText("1번 연습학생21 · 완료",{exact:true}).waitFor();
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"투표 마감하고 개표하기",exact:true}).click();
  await teacher.getByRole("heading",{name:"개표 결과 · 담당 교사 확인용",exact:true}).waitFor();
  assert.match(await teacher.locator("#detail").innerText(),/2표/);
  await observer.getByRole("button",{name:"새로고침",exact:true}).click();
  await observer.getByText("2번 연습학생22 · 완료",{exact:true}).waitFor();
  assert.equal(await observer.getByRole("heading",{name:/개표 결과|공개된 선거 결과/}).count(),0);
  teacher.once("dialog",(dialog)=>dialog.accept("0000"));
  await teacher.getByRole("button",{name:"선거 데이터 삭제",exact:true}).click();
  await teacher.getByText("방번호가 일치하지 않아 삭제하지 않았습니다.",{exact:true}).waitFor();
  await student.reload();
  await student.getByText("투표를 완료했습니다.",{exact:true}).waitFor();
  assert.equal(await student.getByRole("heading",{name:"공개된 선거 결과",exact:true}).count(),0);
  teacher.once("dialog",(dialog)=>dialog.accept());
  await teacher.getByRole("button",{name:"학생들에게 결과 공개",exact:true}).click();
  await teacher.getByRole("heading",{name:"공개된 선거 결과",exact:true}).waitFor();
  await observer.getByRole("button",{name:"새로고침",exact:true}).click();
  await observer.getByRole("heading",{name:"공개된 선거 결과",exact:true}).waitFor();
  await student.reload();
  await student.getByRole("heading",{name:"공개된 선거 결과",exact:true}).waitFor();
  assert.equal(await student.getByRole("button",{name:"선거 데이터 삭제",exact:true}).count(),0);
  await student.screenshot({path:path.join(screenshots,"student-mobile-results.png"),fullPage:true});
  const downloadPromise=teacher.waitForEvent("download");
  await teacher.getByRole("button",{name:"결과 CSV 저장",exact:true}).click();
  assert.match((await downloadPromise).suggestedFilename(),/결과\.csv$/);
  const guest=await browser.newPage();
  await guest.goto(base+"/school-election/?room="+code);
  await guest.getByRole("link",{name:"메인에서 계정 로그인하기 →",exact:true}).waitFor();
  assert.equal(await guest.locator("#joinForm").isVisible(),false);
  await admin.getByRole("button",{name:"새로고침",exact:true}).click();
  await admin.getByRole("button",{name:"선거 데이터 삭제",exact:true}).waitFor();
  assert.equal(await admin.getByRole("button",{name:"선거 열기",exact:true}).count(),0);
  admin.once("dialog",(dialog)=>dialog.dismiss());
  await admin.getByRole("button",{name:"선거 데이터 삭제",exact:true}).click();
  assert.equal(await admin.locator("#electionList .room-card").count(),1);
  admin.once("dialog",(dialog)=>dialog.accept(code));
  await admin.getByRole("button",{name:"선거 데이터 삭제",exact:true}).click();
  await admin.getByText("선거 데이터를 삭제했습니다.",{exact:true}).waitFor();
  assert.equal(await admin.locator("#electionList .room-card").count(),0);
  await student.reload();
  await student.locator("#status").filter({hasText:"전교선거를 찾을 수 없습니다."}).waitFor();

  // Set up another closed election through the same API, then delete through the owner's result screen.
  const created=await teacher.request.post(base+"/api/school-election/elections",{data:{title:"생성자 삭제 확인",year:2026,grades:[3,4,5,6],positions:[{title:"회장",candidates:["후보 가","후보 나"]}]}});
  assert.equal(created.status(),201);
  const ownerElection=(await created.json()).election;
  const ownerUrl=base+"/api/school-election/elections/"+ownerElection.code;
  const ownerDetail=await (await teacher.request.get(ownerUrl)).json();
  assert.equal((await teacher.request.post(ownerUrl+"/start",{data:{rosterVersion:ownerDetail.roster.version}})).status(),200);
  assert.equal((await teacher.request.post(ownerUrl+"/close",{data:{}})).status(),200);
  await teacher.goto(base+"/school-election/?room="+ownerElection.code);
  await teacher.getByRole("button",{name:"선거 데이터 삭제",exact:true}).waitFor();
  teacher.once("dialog",(dialog)=>dialog.accept(ownerElection.code));
  await teacher.getByRole("button",{name:"선거 데이터 삭제",exact:true}).click();
  await teacher.getByText("선거 데이터를 삭제했습니다.",{exact:true}).waitFor();
  assert.equal(await teacher.locator("#electionList .room-card").count(),0);
  assert.deepEqual(errors,[]);
  console.log("Election screenshots: "+screenshots);
});
